/**
 * Mock compliance data for LXP360
 */

import type {
  ComplianceDashboard,
  ComplianceRequirement,
  LearnerComplianceRecord,
  OverdueAssignment,
  UpcomingDeadline,
} from '@/types/lms';

export const mockComplianceRequirements: ComplianceRequirement[] = [
  {
    id: 'req-hipaa',
    name: 'HIPAA Privacy & Security',
    code: 'HIPAA-101',
    description:
      'Annual HIPAA compliance training covering the Privacy Rule, Security Rule, and Breach Notification requirements.',
    type: 'annual',
    regulatoryBody: 'HIPAA',
    frequency: 365,
    gracePeriod: 30,
    expirationWarningDays: [90, 60, 30, 14, 7],
    courseId: 'course-003',
    applicableTo: {
      all: false,
      departments: ['Healthcare', 'IT', 'HR'],
      roles: ['Healthcare Worker', 'Administrator', 'Manager'],
    },
    passingScore: 80,
    attemptsAllowed: 3,
    consequence: 'Employee access to patient data will be revoked until training is completed.',
    escalationPath: ['direct-manager', 'hr-director', 'compliance-officer'],
    autoSuspend: true,
    suspendAfterDays: 30,
    effectiveDate: '2023-01-01',
    version: '3.0',
    isActive: true,
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'req-osha',
    name: 'OSHA Workplace Safety',
    code: 'OSHA-10',
    description:
      'Annual workplace safety training covering hazard identification, PPE, and emergency procedures.',
    type: 'annual',
    regulatoryBody: 'OSHA',
    frequency: 365,
    gracePeriod: 14,
    expirationWarningDays: [60, 30, 14, 7],
    courseId: 'course-004',
    applicableTo: {
      all: false,
      departments: ['Manufacturing', 'Operations', 'Warehouse', 'Facilities'],
    },
    passingScore: 80,
    attemptsAllowed: 3,
    consequence: 'Employee will not be allowed on factory floor until training is completed.',
    escalationPath: ['direct-manager', 'safety-officer', 'hr-director'],
    autoSuspend: true,
    suspendAfterDays: 14,
    effectiveDate: '2023-01-01',
    version: '2.5',
    isActive: true,
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'req-security',
    name: 'Cybersecurity Awareness',
    code: 'SEC-101',
    description:
      'Annual cybersecurity awareness training covering phishing, password security, and data protection.',
    type: 'annual',
    frequency: 365,
    gracePeriod: 30,
    expirationWarningDays: [60, 30, 14, 7],
    courseId: 'course-007',
    applicableTo: {
      all: true,
    },
    passingScore: 80,
    attemptsAllowed: 5,
    consequence: 'System access may be restricted until training is completed.',
    escalationPath: ['direct-manager', 'it-security', 'ciso'],
    autoSuspend: false,
    effectiveDate: '2023-01-01',
    version: '4.0',
    isActive: true,
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-08-01T00:00:00Z',
  },
  {
    id: 'req-harassment',
    name: 'Harassment Prevention',
    code: 'HR-201',
    description: 'Annual training on preventing workplace harassment and discrimination.',
    type: 'annual',
    frequency: 365,
    gracePeriod: 30,
    expirationWarningDays: [60, 30, 14, 7],
    courseId: 'course-harassment',
    applicableTo: {
      all: true,
    },
    passingScore: 80,
    attemptsAllowed: 3,
    consequence: 'Required completion for continued employment.',
    escalationPath: ['direct-manager', 'hr-director', 'legal'],
    autoSuspend: false,
    effectiveDate: '2023-01-01',
    version: '2.0',
    isActive: true,
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-03-01T00:00:00Z',
  },
  {
    id: 'req-onboarding',
    name: 'New Employee Onboarding',
    code: 'ONB-001',
    description:
      'Required onboarding training for all new hires covering company policies, culture, and systems.',
    type: 'onboarding',
    frequency: null,
    gracePeriod: 7,
    expirationWarningDays: [3, 1],
    courseId: 'course-010',
    applicableTo: {
      all: true,
    },
    passingScore: 70,
    attemptsAllowed: 5,
    consequence: 'Must complete within first week of employment.',
    escalationPath: ['direct-manager', 'hr-director'],
    autoSuspend: false,
    effectiveDate: '2023-01-01',
    version: '5.0',
    isActive: true,
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-11-01T00:00:00Z',
  },
];

export const mockLearnerComplianceRecords: LearnerComplianceRecord[] = [
  {
    id: 'lcr-001',
    learnerId: 'learner-001',
    requirementId: 'req-hipaa',
    requirement: mockComplianceRequirements[0],
    status: 'compliant',
    assignedAt: '2024-10-15T00:00:00Z',
    dueDate: '2024-11-15T23:59:59Z',
    completedAt: '2024-11-01T10:30:00Z',
    expiresAt: '2025-11-01T10:30:00Z',
    progress: 100,
    attempts: 1,
    score: 88,
    passed: true,
    certificateId: 'cert-002',
    isExempt: false,
  },
  {
    id: 'lcr-002',
    learnerId: 'learner-001',
    requirementId: 'req-security',
    requirement: mockComplianceRequirements[2],
    status: 'compliant',
    assignedAt: '2024-01-01T00:00:00Z',
    dueDate: '2024-01-31T23:59:59Z',
    completedAt: '2024-01-15T11:00:00Z',
    expiresAt: '2025-01-15T11:00:00Z',
    progress: 100,
    attempts: 1,
    score: 95,
    passed: true,
    isExempt: false,
  },
  {
    id: 'lcr-003',
    learnerId: 'learner-001',
    requirementId: 'req-harassment',
    requirement: mockComplianceRequirements[3],
    status: 'at-risk',
    assignedAt: '2024-11-01T00:00:00Z',
    dueDate: '2024-12-15T23:59:59Z',
    progress: 0,
    attempts: 0,
    isExempt: false,
    lastReminderAt: '2024-12-01T09:00:00Z',
  },
  {
    id: 'lcr-004',
    learnerId: 'learner-002',
    requirementId: 'req-osha',
    requirement: mockComplianceRequirements[1],
    status: 'non-compliant',
    assignedAt: '2024-10-01T00:00:00Z',
    dueDate: '2024-11-30T23:59:59Z',
    gracePeriodEnd: '2024-12-14T23:59:59Z',
    progress: 50,
    attempts: 1,
    isExempt: false,
    lastReminderAt: '2024-12-05T09:00:00Z',
  },
  {
    id: 'lcr-005',
    learnerId: 'learner-002',
    requirementId: 'req-security',
    requirement: mockComplianceRequirements[2],
    status: 'compliant',
    assignedAt: '2024-01-01T00:00:00Z',
    dueDate: '2024-01-31T23:59:59Z',
    completedAt: '2024-01-20T14:00:00Z',
    expiresAt: '2025-01-20T14:00:00Z',
    progress: 100,
    attempts: 2,
    score: 82,
    passed: true,
    isExempt: false,
  },
];

export const mockUpcomingDeadlines: UpcomingDeadline[] = [
  {
    requirementId: 'req-harassment',
    requirementName: 'Harassment Prevention',
    learnerId: 'learner-001',
    learnerName: 'John Smith',
    dueDate: '2024-12-15T23:59:59Z',
    daysRemaining: 7,
    status: 'at-risk',
  },
  {
    requirementId: 'req-security',
    requirementName: 'Cybersecurity Awareness',
    learnerId: 'learner-005',
    learnerName: 'Alex Thompson',
    dueDate: '2024-12-20T23:59:59Z',
    daysRemaining: 12,
    status: 'pending',
  },
  {
    requirementId: 'req-hipaa',
    requirementName: 'HIPAA Privacy & Security',
    learnerId: 'learner-008',
    learnerName: 'Morgan Davis',
    dueDate: '2024-12-25T23:59:59Z',
    daysRemaining: 17,
    status: 'pending',
  },
];

export const mockOverdueAssignments: OverdueAssignment[] = [
  {
    requirementId: 'req-osha',
    requirementName: 'OSHA Workplace Safety',
    learnerId: 'learner-002',
    learnerName: 'Maria Garcia',
    learnerEmail: 'maria.garcia@acmecorp.com',
    managerId: 'manager-002',
    managerName: 'Sarah Miller',
    dueDate: '2024-11-30T23:59:59Z',
    daysOverdue: 8,
    gracePeriodEnd: '2024-12-14T23:59:59Z',
    consequence: 'Employee will not be allowed on factory floor until training is completed.',
  },
  {
    requirementId: 'req-harassment',
    requirementName: 'Harassment Prevention',
    learnerId: 'learner-015',
    learnerName: 'Casey Williams',
    learnerEmail: 'casey.williams@acmecorp.com',
    managerId: 'manager-001',
    managerName: 'John Manager',
    dueDate: '2024-12-01T23:59:59Z',
    daysOverdue: 7,
    consequence: 'Required completion for continued employment.',
  },
];

export const mockComplianceDashboard: ComplianceDashboard = {
  organizationId: 'org-001',
  overallCompliance: 87,
  totalRequirements: 5,
  totalLearners: 500,
  compliant: 385,
  atRisk: 65,
  nonCompliant: 35,
  expired: 10,
  pending: 5,
  exempt: 15,
  requirementStats: [
    {
      requirementId: 'req-hipaa',
      requirementName: 'HIPAA Privacy & Security',
      regulatoryBody: 'HIPAA',
      totalAssigned: 150,
      compliant: 142,
      atRisk: 5,
      nonCompliant: 3,
      complianceRate: 95,
      averageScore: 88,
      nextDeadline: '2024-12-31T23:59:59Z',
    },
    {
      requirementId: 'req-osha',
      requirementName: 'OSHA Workplace Safety',
      regulatoryBody: 'OSHA',
      totalAssigned: 200,
      compliant: 175,
      atRisk: 15,
      nonCompliant: 10,
      complianceRate: 88,
      averageScore: 85,
      nextDeadline: '2024-12-15T23:59:59Z',
    },
    {
      requirementId: 'req-security',
      requirementName: 'Cybersecurity Awareness',
      totalAssigned: 500,
      compliant: 450,
      atRisk: 30,
      nonCompliant: 20,
      complianceRate: 90,
      averageScore: 87,
      nextDeadline: '2024-12-31T23:59:59Z',
    },
    {
      requirementId: 'req-harassment',
      requirementName: 'Harassment Prevention',
      totalAssigned: 500,
      compliant: 420,
      atRisk: 50,
      nonCompliant: 30,
      complianceRate: 84,
      averageScore: 82,
      nextDeadline: '2024-12-15T23:59:59Z',
    },
  ],
  departmentStats: [
    {
      departmentId: 'dept-eng',
      departmentName: 'Engineering',
      learnerCount: 120,
      complianceRate: 92,
      atRiskCount: 8,
      overdueCount: 2,
      requirements: [],
    },
    {
      departmentId: 'dept-healthcare',
      departmentName: 'Healthcare',
      learnerCount: 150,
      complianceRate: 95,
      atRiskCount: 5,
      overdueCount: 3,
      requirements: [],
    },
    {
      departmentId: 'dept-manufacturing',
      departmentName: 'Manufacturing',
      learnerCount: 180,
      complianceRate: 85,
      atRiskCount: 18,
      overdueCount: 9,
      requirements: [],
    },
  ],
  complianceTrend: [
    { date: '2024-07-01', complianceRate: 82, compliant: 350, nonCompliant: 75 },
    { date: '2024-08-01', complianceRate: 84, compliant: 365, nonCompliant: 68 },
    { date: '2024-09-01', complianceRate: 85, compliant: 370, nonCompliant: 65 },
    { date: '2024-10-01', complianceRate: 86, compliant: 378, nonCompliant: 58 },
    { date: '2024-11-01', complianceRate: 87, compliant: 382, nonCompliant: 52 },
    { date: '2024-12-01', complianceRate: 87, compliant: 385, nonCompliant: 50 },
  ],
  upcomingDeadlines: mockUpcomingDeadlines,
  overdueAssignments: mockOverdueAssignments,
  generatedAt: '2024-12-08T00:00:00Z',
};

// Helper functions
export function getComplianceRecordsForLearner(learnerId: string): LearnerComplianceRecord[] {
  return mockLearnerComplianceRecords.filter((r) => r.learnerId === learnerId);
}

export function getOverdueCompliance(learnerId: string): LearnerComplianceRecord[] {
  return mockLearnerComplianceRecords.filter(
    (r) => r.learnerId === learnerId && (r.status === 'non-compliant' || r.status === 'expired'),
  );
}

export function getAtRiskCompliance(learnerId: string): LearnerComplianceRecord[] {
  return mockLearnerComplianceRecords.filter(
    (r) => r.learnerId === learnerId && r.status === 'at-risk',
  );
}

export function isLearnerCompliant(learnerId: string): boolean {
  const records = getComplianceRecordsForLearner(learnerId);
  return records.every((r) => r.status === 'compliant' || r.isExempt);
}
