/**
 * Mock skills data for LXP360
 */

import type { LearnerSkillProgress, Skill, SkillCategory, SkillGapAnalysis } from '@/types/lms';

export const mockSkillCategories: SkillCategory[] = [
  {
    id: 'cat-tech',
    name: 'Technical Skills',
    slug: 'technical',
    description: 'Programming, tools, and technical expertise',
    icon: 'Code',
    color: '#3B82F6',
    order: 1,
    skillCount: 25,
  },
  {
    id: 'cat-leadership',
    name: 'Leadership',
    slug: 'leadership',
    description: 'Management and leadership capabilities',
    icon: 'Users',
    color: '#8B5CF6',
    order: 2,
    skillCount: 12,
  },
  {
    id: 'cat-soft',
    name: 'Soft Skills',
    slug: 'soft-skills',
    description: 'Communication, collaboration, and interpersonal skills',
    icon: 'MessageCircle',
    color: '#EC4899',
    order: 3,
    skillCount: 15,
  },
  {
    id: 'cat-compliance',
    name: 'Compliance',
    slug: 'compliance',
    description: 'Regulatory and compliance knowledge',
    icon: 'Shield',
    color: '#10B981',
    order: 4,
    skillCount: 18,
  },
  {
    id: 'cat-business',
    name: 'Business',
    slug: 'business',
    description: 'Business strategy and operations',
    icon: 'Briefcase',
    color: '#F59E0B',
    order: 5,
    skillCount: 14,
  },
  {
    id: 'cat-safety',
    name: 'Safety',
    slug: 'safety',
    description: 'Workplace and industrial safety',
    icon: 'AlertTriangle',
    color: '#EF4444',
    order: 6,
    skillCount: 10,
  },
];

export const mockSkills: Skill[] = [
  // Technical Skills
  {
    id: 'skill-js',
    name: 'JavaScript',
    slug: 'javascript',
    description: 'Modern JavaScript programming including ES6+, async patterns, and frameworks',
    category: mockSkillCategories[0],
    icon: 'FileCode',
    color: '#F7DF1E',
    levels: [
      {
        level: 1,
        name: 'novice',
        description: 'Basic syntax and concepts',
        requirements: ['Complete intro course'],
        minScore: 0,
        xpRequired: 0,
      },
      {
        level: 2,
        name: 'beginner',
        description: 'Core language features',
        requirements: ['Variables, functions, loops'],
        minScore: 20,
        xpRequired: 500,
      },
      {
        level: 3,
        name: 'intermediate',
        description: 'ES6+ and async programming',
        requirements: ['Promises, async/await'],
        minScore: 40,
        xpRequired: 1500,
      },
      {
        level: 4,
        name: 'advanced',
        description: 'Advanced patterns and optimization',
        requirements: ['Design patterns, performance'],
        minScore: 60,
        xpRequired: 3000,
      },
      {
        level: 5,
        name: 'expert',
        description: 'Framework expertise and architecture',
        requirements: ['Build complex applications'],
        minScore: 80,
        xpRequired: 5000,
      },
    ],
    maxLevel: 5,
    courseCount: 8,
    learnerCount: 12500,
    assessmentCount: 4,
    isCore: true,
    isRequired: false,
    prerequisites: [],
    relatedSkills: ['skill-react', 'skill-nodejs', 'skill-typescript'],
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-11-01T00:00:00Z',
  },
  {
    id: 'skill-react',
    name: 'React',
    slug: 'react',
    description:
      'Building user interfaces with React including hooks, state management, and Next.js',
    category: mockSkillCategories[0],
    icon: 'Layers',
    color: '#61DAFB',
    levels: [
      {
        level: 1,
        name: 'novice',
        description: 'Basic components and JSX',
        requirements: [],
        minScore: 0,
        xpRequired: 0,
      },
      {
        level: 2,
        name: 'beginner',
        description: 'State and props management',
        requirements: [],
        minScore: 20,
        xpRequired: 500,
      },
      {
        level: 3,
        name: 'intermediate',
        description: 'Hooks and context',
        requirements: [],
        minScore: 40,
        xpRequired: 1500,
      },
      {
        level: 4,
        name: 'advanced',
        description: 'Performance optimization',
        requirements: [],
        minScore: 60,
        xpRequired: 3000,
      },
      {
        level: 5,
        name: 'expert',
        description: 'Architecture and patterns',
        requirements: [],
        minScore: 80,
        xpRequired: 5000,
      },
    ],
    maxLevel: 5,
    courseCount: 6,
    learnerCount: 8900,
    assessmentCount: 3,
    isCore: true,
    isRequired: false,
    prerequisites: ['skill-js'],
    relatedSkills: ['skill-js', 'skill-nextjs', 'skill-typescript'],
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-11-01T00:00:00Z',
  },
  {
    id: 'skill-python',
    name: 'Python',
    slug: 'python',
    description: 'Python programming for data science, automation, and web development',
    category: mockSkillCategories[0],
    icon: 'FileCode',
    color: '#3776AB',
    levels: [
      {
        level: 1,
        name: 'novice',
        description: 'Basic syntax',
        requirements: [],
        minScore: 0,
        xpRequired: 0,
      },
      {
        level: 2,
        name: 'beginner',
        description: 'Data structures',
        requirements: [],
        minScore: 20,
        xpRequired: 500,
      },
      {
        level: 3,
        name: 'intermediate',
        description: 'Libraries and frameworks',
        requirements: [],
        minScore: 40,
        xpRequired: 1500,
      },
      {
        level: 4,
        name: 'advanced',
        description: 'Data science tools',
        requirements: [],
        minScore: 60,
        xpRequired: 3000,
      },
      {
        level: 5,
        name: 'expert',
        description: 'ML and advanced applications',
        requirements: [],
        minScore: 80,
        xpRequired: 5000,
      },
    ],
    maxLevel: 5,
    courseCount: 10,
    learnerCount: 15600,
    assessmentCount: 5,
    isCore: true,
    isRequired: false,
    prerequisites: [],
    relatedSkills: ['skill-analytics', 'skill-ml'],
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-11-01T00:00:00Z',
  },
  // Leadership Skills
  {
    id: 'skill-leadership',
    name: 'Leadership',
    slug: 'leadership',
    description: 'Leading teams, making decisions, and inspiring others to achieve goals',
    category: mockSkillCategories[1],
    icon: 'Crown',
    color: '#8B5CF6',
    levels: [
      {
        level: 1,
        name: 'novice',
        description: 'Self-leadership',
        requirements: [],
        minScore: 0,
        xpRequired: 0,
      },
      {
        level: 2,
        name: 'beginner',
        description: 'Leading small teams',
        requirements: [],
        minScore: 20,
        xpRequired: 500,
      },
      {
        level: 3,
        name: 'intermediate',
        description: 'Project leadership',
        requirements: [],
        minScore: 40,
        xpRequired: 1500,
      },
      {
        level: 4,
        name: 'advanced',
        description: 'Organizational influence',
        requirements: [],
        minScore: 60,
        xpRequired: 3000,
      },
      {
        level: 5,
        name: 'expert',
        description: 'Executive leadership',
        requirements: [],
        minScore: 80,
        xpRequired: 5000,
      },
    ],
    maxLevel: 5,
    courseCount: 5,
    learnerCount: 8500,
    assessmentCount: 2,
    isCore: true,
    isRequired: false,
    prerequisites: [],
    relatedSkills: ['skill-communication', 'skill-eq', 'skill-strategy'],
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-11-01T00:00:00Z',
  },
  {
    id: 'skill-eq',
    name: 'Emotional Intelligence',
    slug: 'emotional-intelligence',
    description: 'Understanding and managing emotions in yourself and others',
    category: mockSkillCategories[1],
    icon: 'Heart',
    color: '#EC4899',
    levels: [
      {
        level: 1,
        name: 'novice',
        description: 'Self-awareness basics',
        requirements: [],
        minScore: 0,
        xpRequired: 0,
      },
      {
        level: 2,
        name: 'beginner',
        description: 'Emotion recognition',
        requirements: [],
        minScore: 20,
        xpRequired: 400,
      },
      {
        level: 3,
        name: 'intermediate',
        description: 'Self-regulation',
        requirements: [],
        minScore: 40,
        xpRequired: 1200,
      },
      {
        level: 4,
        name: 'advanced',
        description: 'Social awareness',
        requirements: [],
        minScore: 60,
        xpRequired: 2500,
      },
      {
        level: 5,
        name: 'expert',
        description: 'Relationship management',
        requirements: [],
        minScore: 80,
        xpRequired: 4000,
      },
    ],
    maxLevel: 5,
    courseCount: 4,
    learnerCount: 6200,
    assessmentCount: 2,
    isCore: false,
    isRequired: false,
    prerequisites: [],
    relatedSkills: ['skill-leadership', 'skill-communication'],
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-11-01T00:00:00Z',
  },
  // Soft Skills
  {
    id: 'skill-communication',
    name: 'Communication',
    slug: 'communication',
    description: 'Effective verbal, written, and presentation communication',
    category: mockSkillCategories[2],
    icon: 'MessageSquare',
    color: '#06B6D4',
    levels: [
      {
        level: 1,
        name: 'novice',
        description: 'Basic communication',
        requirements: [],
        minScore: 0,
        xpRequired: 0,
      },
      {
        level: 2,
        name: 'beginner',
        description: 'Clear messaging',
        requirements: [],
        minScore: 20,
        xpRequired: 400,
      },
      {
        level: 3,
        name: 'intermediate',
        description: 'Persuasive communication',
        requirements: [],
        minScore: 40,
        xpRequired: 1200,
      },
      {
        level: 4,
        name: 'advanced',
        description: 'Executive presence',
        requirements: [],
        minScore: 60,
        xpRequired: 2500,
      },
      {
        level: 5,
        name: 'expert',
        description: 'Strategic communication',
        requirements: [],
        minScore: 80,
        xpRequired: 4000,
      },
    ],
    maxLevel: 5,
    courseCount: 6,
    learnerCount: 14500,
    assessmentCount: 3,
    isCore: true,
    isRequired: false,
    prerequisites: [],
    relatedSkills: ['skill-presentation', 'skill-leadership'],
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-11-01T00:00:00Z',
  },
  // Compliance Skills
  {
    id: 'skill-hipaa',
    name: 'HIPAA Compliance',
    slug: 'hipaa-compliance',
    description: 'Healthcare privacy and security regulations compliance',
    category: mockSkillCategories[3],
    icon: 'Shield',
    color: '#10B981',
    levels: [
      {
        level: 1,
        name: 'novice',
        description: 'HIPAA basics',
        requirements: [],
        minScore: 0,
        xpRequired: 0,
      },
      {
        level: 2,
        name: 'beginner',
        description: 'Privacy Rule',
        requirements: [],
        minScore: 30,
        xpRequired: 300,
      },
      {
        level: 3,
        name: 'intermediate',
        description: 'Security Rule',
        requirements: [],
        minScore: 50,
        xpRequired: 800,
      },
      {
        level: 4,
        name: 'advanced',
        description: 'Breach notification',
        requirements: [],
        minScore: 70,
        xpRequired: 1500,
      },
      {
        level: 5,
        name: 'expert',
        description: 'Compliance management',
        requirements: [],
        minScore: 90,
        xpRequired: 2500,
      },
    ],
    maxLevel: 5,
    courseCount: 4,
    learnerCount: 28000,
    assessmentCount: 2,
    isCore: true,
    isRequired: true,
    departmentIds: ['dept-healthcare'],
    prerequisites: [],
    relatedSkills: ['skill-privacy', 'skill-security'],
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-11-01T00:00:00Z',
  },
  {
    id: 'skill-osha',
    name: 'OSHA Compliance',
    slug: 'osha-compliance',
    description: 'Workplace safety regulations and OSHA standards',
    category: mockSkillCategories[5],
    icon: 'HardHat',
    color: '#F59E0B',
    levels: [
      {
        level: 1,
        name: 'novice',
        description: 'Safety awareness',
        requirements: [],
        minScore: 0,
        xpRequired: 0,
      },
      {
        level: 2,
        name: 'beginner',
        description: 'Hazard identification',
        requirements: [],
        minScore: 30,
        xpRequired: 300,
      },
      {
        level: 3,
        name: 'intermediate',
        description: 'PPE and controls',
        requirements: [],
        minScore: 50,
        xpRequired: 800,
      },
      {
        level: 4,
        name: 'advanced',
        description: 'Incident management',
        requirements: [],
        minScore: 70,
        xpRequired: 1500,
      },
      {
        level: 5,
        name: 'expert',
        description: 'Safety program management',
        requirements: [],
        minScore: 90,
        xpRequired: 2500,
      },
    ],
    maxLevel: 5,
    courseCount: 6,
    learnerCount: 45000,
    assessmentCount: 3,
    isCore: true,
    isRequired: true,
    departmentIds: ['dept-manufacturing', 'dept-operations'],
    prerequisites: [],
    relatedSkills: ['skill-safety', 'skill-emergency'],
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-11-01T00:00:00Z',
  },
  // Business Skills
  {
    id: 'skill-pm-pro',
    name: 'Project Management',
    slug: 'project-management',
    description: 'Planning, executing, and managing projects using various methodologies',
    category: mockSkillCategories[4],
    icon: 'ClipboardList',
    color: '#6366F1',
    levels: [
      {
        level: 1,
        name: 'novice',
        description: 'PM fundamentals',
        requirements: [],
        minScore: 0,
        xpRequired: 0,
      },
      {
        level: 2,
        name: 'beginner',
        description: 'Planning and scheduling',
        requirements: [],
        minScore: 20,
        xpRequired: 600,
      },
      {
        level: 3,
        name: 'intermediate',
        description: 'Risk and stakeholder management',
        requirements: [],
        minScore: 40,
        xpRequired: 1800,
      },
      {
        level: 4,
        name: 'advanced',
        description: 'Program management',
        requirements: [],
        minScore: 60,
        xpRequired: 3500,
      },
      {
        level: 5,
        name: 'expert',
        description: 'Portfolio management',
        requirements: [],
        minScore: 80,
        xpRequired: 6000,
      },
    ],
    maxLevel: 5,
    courseCount: 5,
    learnerCount: 9800,
    assessmentCount: 4,
    isCore: true,
    isRequired: false,
    prerequisites: [],
    relatedSkills: ['skill-agile', 'skill-leadership'],
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-11-01T00:00:00Z',
  },
  {
    id: 'skill-analytics',
    name: 'Data Analytics',
    slug: 'data-analytics',
    description: 'Analyzing data to extract insights and drive decisions',
    category: mockSkillCategories[0],
    icon: 'BarChart2',
    color: '#14B8A6',
    levels: [
      {
        level: 1,
        name: 'novice',
        description: 'Data basics',
        requirements: [],
        minScore: 0,
        xpRequired: 0,
      },
      {
        level: 2,
        name: 'beginner',
        description: 'Data cleaning',
        requirements: [],
        minScore: 20,
        xpRequired: 500,
      },
      {
        level: 3,
        name: 'intermediate',
        description: 'Statistical analysis',
        requirements: [],
        minScore: 40,
        xpRequired: 1500,
      },
      {
        level: 4,
        name: 'advanced',
        description: 'Predictive analytics',
        requirements: [],
        minScore: 60,
        xpRequired: 3000,
      },
      {
        level: 5,
        name: 'expert',
        description: 'Advanced modeling',
        requirements: [],
        minScore: 80,
        xpRequired: 5000,
      },
    ],
    maxLevel: 5,
    courseCount: 7,
    learnerCount: 11200,
    assessmentCount: 4,
    isCore: true,
    isRequired: false,
    prerequisites: [],
    relatedSkills: ['skill-python', 'skill-sql', 'skill-ml'],
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-11-01T00:00:00Z',
  },
];

export const mockLearnerSkillProgress: LearnerSkillProgress[] = [
  {
    skillId: 'skill-js',
    learnerId: 'learner-001',
    currentLevel: 3,
    currentScore: 68,
    xp: 1850,
    xpToNextLevel: 1150,
    levelName: 'intermediate',
    progressHistory: [
      {
        date: '2024-09-01',
        level: 2,
        score: 35,
        source: 'course',
        sourceId: 'course-001',
        delta: 15,
      },
      {
        date: '2024-10-15',
        level: 3,
        score: 55,
        source: 'assessment',
        sourceId: 'quiz-js-01',
        delta: 20,
      },
      {
        date: '2024-11-20',
        level: 3,
        score: 68,
        source: 'course',
        sourceId: 'course-002',
        delta: 13,
      },
    ],
    assessments: [
      {
        assessmentId: 'quiz-js-01',
        assessmentTitle: 'JavaScript Fundamentals',
        takenAt: '2024-10-15',
        score: 85,
        level: 'intermediate',
        passed: true,
      },
    ],
    endorsements: [
      {
        id: 'endorse-001',
        endorserId: 'learner-005',
        endorserName: 'Alex Thompson',
        relationship: 'peer',
        endorsedAt: '2024-11-01',
      },
    ],
    courses: [
      {
        courseId: 'course-001',
        courseTitle: 'JavaScript Fundamentals',
        contribution: 30,
        completedAt: '2024-09-15',
        status: 'completed',
      },
      {
        courseId: 'course-002',
        courseTitle: 'React & Next.js',
        contribution: 38,
        status: 'in-progress',
      },
    ],
    lastAssessedAt: '2024-10-15',
    lastActivityAt: '2024-11-20',
    trend: 'improving',
  },
];

export const mockSkillGapAnalysis: SkillGapAnalysis = {
  learnerId: 'learner-001',
  targetRole: 'Senior Software Engineer',
  skills: [
    {
      skillId: 'skill-js',
      skillName: 'JavaScript',
      currentLevel: 68,
      targetLevel: 85,
      gap: 17,
      priority: 'high',
      courses: [
        {
          courseId: 'course-advanced-js',
          courseTitle: 'Advanced JavaScript Patterns',
          levelGain: 15,
        },
      ],
      estimatedTime: 20,
    },
    {
      skillId: 'skill-react',
      skillName: 'React',
      currentLevel: 55,
      targetLevel: 80,
      gap: 25,
      priority: 'critical',
      courses: [
        { courseId: 'course-002', courseTitle: 'React & Next.js', levelGain: 20 },
        {
          courseId: 'course-react-advanced',
          courseTitle: 'Advanced React Patterns',
          levelGain: 10,
        },
      ],
      estimatedTime: 35,
    },
    {
      skillId: 'skill-leadership',
      skillName: 'Leadership',
      currentLevel: 45,
      targetLevel: 60,
      gap: 15,
      priority: 'medium',
      courses: [{ courseId: 'course-005', courseTitle: 'Leadership Excellence', levelGain: 20 }],
      estimatedTime: 15,
    },
  ],
  overallReadiness: 65,
  estimatedTimeToClose: 70,
  recommendedCourses: ['course-002', 'course-advanced-js', 'course-005'],
  recommendedPaths: ['path-001'],
  generatedAt: '2024-12-01T00:00:00Z',
};

// Helper functions
export function getSkillById(id: string): Skill | undefined {
  return mockSkills.find((skill) => skill.id === id);
}

export function getSkillsByCategory(categoryId: string): Skill[] {
  return mockSkills.filter((skill) => skill.category.id === categoryId);
}

export function getRequiredSkills(): Skill[] {
  return mockSkills.filter((skill) => skill.isRequired);
}
