/**
 * Mock badges and achievements data for LXP360
 *
 * @deprecated Use Firestore services instead. See lib/firestore/services/achievements.ts
 * This file is retained for seed script reference only.
 */

import type {
  Badge,
  Certificate,
  EarnedBadge,
  GamificationProfile,
  Leaderboard,
  LevelDefinition,
  Reward,
} from '@/types/lms';

export const mockLevelDefinitions: LevelDefinition[] = [
  { level: 1, name: 'Newcomer', minXp: 0, maxXp: 499, icon: 'Sprout', color: '#9CA3AF' },
  { level: 2, name: 'Learner', minXp: 500, maxXp: 1499, icon: 'BookOpen', color: '#60A5FA' },
  { level: 3, name: 'Explorer', minXp: 1500, maxXp: 2999, icon: 'Compass', color: '#34D399' },
  { level: 4, name: 'Achiever', minXp: 3000, maxXp: 4999, icon: 'Target', color: '#A78BFA' },
  { level: 5, name: 'Expert', minXp: 5000, maxXp: 7499, icon: 'Award', color: '#F472B6' },
  { level: 6, name: 'Master', minXp: 7500, maxXp: 9999, icon: 'Crown', color: '#FBBF24' },
  { level: 7, name: 'Champion', minXp: 10000, maxXp: 14999, icon: 'Trophy', color: '#F97316' },
  { level: 8, name: 'Legend', minXp: 15000, maxXp: 24999, icon: 'Star', color: '#EF4444' },
  { level: 9, name: 'Elite', minXp: 25000, maxXp: 49999, icon: 'Gem', color: '#EC4899' },
  { level: 10, name: 'Grandmaster', minXp: 50000, maxXp: 999999, icon: 'Zap', color: '#8B5CF6' },
];

export const mockBadges: Badge[] = [
  // Course Completion Badges
  {
    id: 'badge-first-course',
    name: 'First Steps',
    slug: 'first-steps',
    description: 'Complete your first course on the platform',
    shortDescription: 'Complete first course',
    icon: 'Rocket',
    image: '/badges/first-steps.png',
    rarity: 'common',
    category: 'completion',
    type: 'completion',
    criteria: {
      type: 'completion',
      conditions: [{ metric: 'courses_completed', operator: 'gte', value: 1 }],
      allRequired: true,
    },
    xpReward: 100,
    pointsReward: 50,
    isHidden: false,
    isStackable: false,
    maxStack: 1,
    earnedCount: 45000,
    earnedPercentage: 95,
    createdAt: '2023-01-01T00:00:00Z',
    isActive: true,
  },
  {
    id: 'badge-course-veteran',
    name: 'Course Veteran',
    slug: 'course-veteran',
    description: 'Complete 10 courses and become a learning veteran',
    shortDescription: 'Complete 10 courses',
    icon: 'Medal',
    image: '/badges/course-veteran.png',
    rarity: 'uncommon',
    category: 'completion',
    type: 'milestone',
    criteria: {
      type: 'milestone',
      conditions: [{ metric: 'courses_completed', operator: 'gte', value: 10 }],
      allRequired: true,
    },
    xpReward: 500,
    pointsReward: 250,
    isHidden: false,
    isStackable: false,
    maxStack: 1,
    earnedCount: 12000,
    earnedPercentage: 25,
    createdAt: '2023-01-01T00:00:00Z',
    isActive: true,
  },
  {
    id: 'badge-course-master',
    name: 'Course Master',
    slug: 'course-master',
    description: 'Complete 50 courses and demonstrate dedication to learning',
    shortDescription: 'Complete 50 courses',
    icon: 'Crown',
    image: '/badges/course-master.png',
    rarity: 'epic',
    category: 'completion',
    type: 'milestone',
    criteria: {
      type: 'milestone',
      conditions: [{ metric: 'courses_completed', operator: 'gte', value: 50 }],
      allRequired: true,
    },
    xpReward: 2000,
    pointsReward: 1000,
    isHidden: false,
    isStackable: false,
    maxStack: 1,
    earnedCount: 890,
    earnedPercentage: 2,
    createdAt: '2023-01-01T00:00:00Z',
    isActive: true,
  },
  // Streak Badges
  {
    id: 'badge-streak-7',
    name: 'Week Warrior',
    slug: 'week-warrior',
    description: 'Maintain a 7-day learning streak',
    shortDescription: '7-day streak',
    icon: 'Flame',
    image: '/badges/week-warrior.png',
    rarity: 'common',
    category: 'streak',
    type: 'streak',
    criteria: {
      type: 'streak',
      conditions: [{ metric: 'streak_days', operator: 'gte', value: 7 }],
      allRequired: true,
    },
    xpReward: 150,
    pointsReward: 75,
    isHidden: false,
    isStackable: true,
    maxStack: 52,
    earnedCount: 25000,
    earnedPercentage: 52,
    createdAt: '2023-01-01T00:00:00Z',
    isActive: true,
  },
  {
    id: 'badge-streak-30',
    name: 'Monthly Master',
    slug: 'monthly-master',
    description: 'Maintain a 30-day learning streak',
    shortDescription: '30-day streak',
    icon: 'Flame',
    image: '/badges/monthly-master.png',
    rarity: 'rare',
    category: 'streak',
    type: 'streak',
    criteria: {
      type: 'streak',
      conditions: [{ metric: 'streak_days', operator: 'gte', value: 30 }],
      allRequired: true,
    },
    xpReward: 750,
    pointsReward: 400,
    isHidden: false,
    isStackable: true,
    maxStack: 12,
    earnedCount: 5600,
    earnedPercentage: 12,
    createdAt: '2023-01-01T00:00:00Z',
    isActive: true,
  },
  {
    id: 'badge-streak-100',
    name: 'Century Learner',
    slug: 'century-learner',
    description: 'Maintain a 100-day learning streak',
    shortDescription: '100-day streak',
    icon: 'Flame',
    image: '/badges/century-learner.png',
    rarity: 'legendary',
    category: 'streak',
    type: 'streak',
    criteria: {
      type: 'streak',
      conditions: [{ metric: 'streak_days', operator: 'gte', value: 100 }],
      allRequired: true,
    },
    xpReward: 3000,
    pointsReward: 1500,
    isHidden: false,
    isStackable: true,
    maxStack: 3,
    earnedCount: 234,
    earnedPercentage: 0.5,
    createdAt: '2023-01-01T00:00:00Z',
    isActive: true,
  },
  // Score Badges
  {
    id: 'badge-perfect-score',
    name: 'Perfect Score',
    slug: 'perfect-score',
    description: 'Achieve 100% on unknown quiz or assessment',
    shortDescription: 'Score 100% on quiz',
    icon: 'Target',
    image: '/badges/perfect-score.png',
    rarity: 'uncommon',
    category: 'score',
    type: 'score',
    criteria: {
      type: 'score',
      conditions: [{ metric: 'quiz_score', operator: 'eq', value: 100 }],
      allRequired: true,
    },
    xpReward: 200,
    pointsReward: 100,
    isHidden: false,
    isStackable: true,
    maxStack: 100,
    earnedCount: 18000,
    earnedPercentage: 38,
    createdAt: '2023-01-01T00:00:00Z',
    isActive: true,
  },
  // Skill Badges
  {
    id: 'badge-js-fundamentals',
    name: 'JavaScript Fundamentalist',
    slug: 'javascript-fundamentalist',
    description: 'Complete JavaScript Fundamentals course with 80%+ score',
    shortDescription: 'Master JS basics',
    icon: 'Code',
    image: '/badges/js-fundamentalist.png',
    rarity: 'common',
    category: 'skill',
    type: 'skill',
    criteria: {
      type: 'skill',
      conditions: [
        { metric: 'course_completed', operator: 'eq', value: 1, courseId: 'course-001' },
        { metric: 'course_score', operator: 'gte', value: 80, courseId: 'course-001' },
      ],
      allRequired: true,
    },
    xpReward: 300,
    pointsReward: 150,
    isHidden: false,
    isStackable: false,
    maxStack: 1,
    earnedCount: 10500,
    earnedPercentage: 22,
    createdAt: '2023-01-01T00:00:00Z',
    isActive: true,
  },
  {
    id: 'badge-react-developer',
    name: 'React Developer',
    slug: 'react-developer',
    description: 'Complete React & Next.js course and build your first app',
    shortDescription: 'Learn React',
    icon: 'Layers',
    image: '/badges/react-developer.png',
    rarity: 'uncommon',
    category: 'skill',
    type: 'skill',
    criteria: {
      type: 'skill',
      conditions: [
        { metric: 'course_completed', operator: 'eq', value: 1, courseId: 'course-002' },
      ],
      allRequired: true,
    },
    xpReward: 500,
    pointsReward: 250,
    isHidden: false,
    isStackable: false,
    maxStack: 1,
    earnedCount: 6300,
    earnedPercentage: 13,
    createdAt: '2023-01-01T00:00:00Z',
    isActive: true,
  },
  // Compliance Badges
  {
    id: 'badge-hipaa-certified',
    name: 'HIPAA Certified',
    slug: 'hipaa-certified',
    description: 'Complete HIPAA compliance training with passing score',
    shortDescription: 'HIPAA certified',
    icon: 'Shield',
    image: '/badges/hipaa-certified.png',
    rarity: 'common',
    category: 'compliance',
    type: 'completion',
    criteria: {
      type: 'completion',
      conditions: [
        { metric: 'course_completed', operator: 'eq', value: 1, courseId: 'course-003' },
        { metric: 'course_score', operator: 'gte', value: 80 },
      ],
      allRequired: true,
    },
    xpReward: 250,
    pointsReward: 100,
    isHidden: false,
    isStackable: true,
    maxStack: 10,
    earnedCount: 26500,
    earnedPercentage: 55,
    createdAt: '2023-01-01T00:00:00Z',
    isActive: true,
  },
  {
    id: 'badge-osha-certified',
    name: 'OSHA Certified',
    slug: 'osha-certified',
    description: 'Complete OSHA workplace safety training',
    shortDescription: 'OSHA certified',
    icon: 'HardHat',
    image: '/badges/osha-certified.png',
    rarity: 'common',
    category: 'compliance',
    type: 'completion',
    criteria: {
      type: 'completion',
      conditions: [
        { metric: 'course_completed', operator: 'eq', value: 1, courseId: 'course-004' },
      ],
      allRequired: true,
    },
    xpReward: 250,
    pointsReward: 100,
    isHidden: false,
    isStackable: true,
    maxStack: 10,
    earnedCount: 42000,
    earnedPercentage: 88,
    createdAt: '2023-01-01T00:00:00Z',
    isActive: true,
  },
  {
    id: 'badge-security-aware',
    name: 'Security Champion',
    slug: 'security-champion',
    description: 'Complete cybersecurity awareness training',
    shortDescription: 'Security trained',
    icon: 'Lock',
    image: '/badges/security-champion.png',
    rarity: 'common',
    category: 'compliance',
    type: 'completion',
    criteria: {
      type: 'completion',
      conditions: [
        { metric: 'course_completed', operator: 'eq', value: 1, courseId: 'course-007' },
      ],
      allRequired: true,
    },
    xpReward: 150,
    pointsReward: 75,
    isHidden: false,
    isStackable: true,
    maxStack: 5,
    earnedCount: 48000,
    earnedPercentage: 92,
    createdAt: '2023-01-01T00:00:00Z',
    isActive: true,
  },
  // Leadership Badges
  {
    id: 'badge-leader',
    name: 'Emerging Leader',
    slug: 'emerging-leader',
    description: 'Complete the Leadership Excellence course',
    shortDescription: 'Leadership trained',
    icon: 'Crown',
    image: '/badges/emerging-leader.png',
    rarity: 'rare',
    category: 'skill',
    type: 'skill',
    criteria: {
      type: 'skill',
      conditions: [
        { metric: 'course_completed', operator: 'eq', value: 1, courseId: 'course-005' },
      ],
      allRequired: true,
    },
    xpReward: 600,
    pointsReward: 300,
    isHidden: false,
    isStackable: false,
    maxStack: 1,
    earnedCount: 7500,
    earnedPercentage: 16,
    createdAt: '2023-01-01T00:00:00Z',
    isActive: true,
  },
  // Social Badges
  {
    id: 'badge-helpful',
    name: 'Helpful Hero',
    slug: 'helpful-hero',
    description: 'Have 10 answers marked as helpful in discussions',
    shortDescription: 'Help others',
    icon: 'HandHeart',
    image: '/badges/helpful-hero.png',
    rarity: 'rare',
    category: 'social',
    type: 'social',
    criteria: {
      type: 'social',
      conditions: [{ metric: 'helpful_answers', operator: 'gte', value: 10 }],
      allRequired: true,
    },
    xpReward: 400,
    pointsReward: 200,
    isHidden: false,
    isStackable: true,
    maxStack: 10,
    earnedCount: 2300,
    earnedPercentage: 5,
    createdAt: '2023-01-01T00:00:00Z',
    isActive: true,
  },
  // Special/Hidden Badges
  {
    id: 'badge-early-bird',
    name: 'Early Bird',
    slug: 'early-bird',
    description: 'Complete a learning activity before 6 AM',
    shortDescription: 'Learn before 6 AM',
    icon: 'Sun',
    image: '/badges/early-bird.png',
    rarity: 'rare',
    category: 'special',
    type: 'special',
    criteria: {
      type: 'special',
      conditions: [{ metric: 'activity_time', operator: 'lt', value: 6 }],
      allRequired: true,
    },
    xpReward: 200,
    pointsReward: 100,
    isHidden: true,
    isStackable: false,
    maxStack: 1,
    earnedCount: 3400,
    earnedPercentage: 7,
    createdAt: '2023-01-01T00:00:00Z',
    isActive: true,
  },
];

export const mockEarnedBadges: EarnedBadge[] = [
  {
    id: 'earned-001',
    badgeId: 'badge-first-course',
    badge: mockBadges[0],
    learnerId: 'learner-001',
    earnedAt: '2024-06-20T14:30:00Z',
    source: { type: 'course', id: 'course-001', title: 'JavaScript Fundamentals' },
    stackCount: 1,
    isDisplayed: true,
    shareUrl: 'https://lxp360.com/badges/earned-001',
  },
  {
    id: 'earned-002',
    badgeId: 'badge-streak-7',
    badge: mockBadges[3],
    learnerId: 'learner-001',
    earnedAt: '2024-10-15T09:00:00Z',
    source: { type: 'streak' },
    stackCount: 8,
    isDisplayed: true,
  },
  {
    id: 'earned-003',
    badgeId: 'badge-js-fundamentals',
    badge: mockBadges[7],
    learnerId: 'learner-001',
    earnedAt: '2024-09-15T16:45:00Z',
    source: { type: 'course', id: 'course-001', title: 'JavaScript Fundamentals' },
    stackCount: 1,
    isDisplayed: true,
  },
];

export const mockCertificates: Certificate[] = [
  {
    id: 'cert-001',
    templateId: 'template-tech-001',
    learnerId: 'learner-001',
    learnerName: 'John Smith',
    courseId: 'course-001',
    title: 'JavaScript Fundamentals',
    description: 'Successfully completed the JavaScript Fundamentals course with excellence.',
    issuedAt: '2024-09-15T16:45:00Z',
    completionDate: '2024-09-15',
    score: 92,
    hours: 8,
    credits: 2,
    instructor: 'James Wilson',
    organization: 'LXD360 Learning',
    credentialId: 'LXD-JS-2024-0915-001',
    verificationCode: 'VXYZ1234ABCD',
    verificationUrl: 'https://lxp360.com/verify/VXYZ1234ABCD',
    status: 'issued',
    pdfUrl: '/certificates/cert-001.pdf',
    imageUrl: '/certificates/cert-001.png',
    linkedInAddUrl: 'https://www.linkedin.com/profile/add?startTask=CERTIFICATION_NAME',
  },
  {
    id: 'cert-002',
    templateId: 'template-compliance-001',
    learnerId: 'learner-001',
    learnerName: 'John Smith',
    courseId: 'course-003',
    title: 'HIPAA Compliance Certification',
    description: 'Completed annual HIPAA privacy and security training.',
    issuedAt: '2024-11-01T10:30:00Z',
    expiresAt: '2025-11-01T10:30:00Z',
    validityPeriod: 12,
    completionDate: '2024-11-01',
    score: 88,
    hours: 1.5,
    ceuCredits: 1.5,
    instructor: 'Dr. Emily Rodriguez',
    organization: 'LXD360 Learning',
    credentialId: 'LXD-HIPAA-2024-1101-001',
    verificationCode: 'HIPAA1234XYZ',
    verificationUrl: 'https://lxp360.com/verify/HIPAA1234XYZ',
    status: 'issued',
    pdfUrl: '/certificates/cert-002.pdf',
    imageUrl: '/certificates/cert-002.png',
  },
];

export const mockLeaderboard: Leaderboard = {
  id: 'lb-global-monthly',
  name: 'Monthly Champions',
  type: 'global',
  metric: 'xp',
  period: 'monthly',
  entries: [
    {
      rank: 1,
      learnerId: 'learner-010',
      learnerName: 'Alex Thompson',
      learnerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
      score: 4520,
      level: 15,
      change: 2,
      trend: 'up',
    },
    {
      rank: 2,
      learnerId: 'learner-005',
      learnerName: 'Jordan Chen',
      learnerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan',
      score: 4280,
      level: 14,
      change: -1,
      trend: 'down',
    },
    {
      rank: 3,
      learnerId: 'learner-012',
      learnerName: 'Taylor Martinez',
      learnerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Taylor',
      score: 3950,
      level: 13,
      change: 5,
      trend: 'up',
    },
    {
      rank: 4,
      learnerId: 'learner-001',
      learnerName: 'John Smith',
      learnerAvatar: 'https://images.unsplash.com/photo-1599566150163-29194dcabd36?w=150',
      score: 3720,
      level: 12,
      change: 0,
      trend: 'same',
    },
    {
      rank: 5,
      learnerId: 'learner-008',
      learnerName: 'Morgan Davis',
      learnerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Morgan',
      score: 3580,
      level: 12,
      change: -2,
      trend: 'down',
    },
    {
      rank: 6,
      learnerId: 'learner-015',
      learnerName: 'Casey Williams',
      learnerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Casey',
      score: 3420,
      level: 11,
      change: 1,
      trend: 'up',
    },
    {
      rank: 7,
      learnerId: 'learner-002',
      learnerName: 'Maria Garcia',
      learnerAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
      score: 3180,
      level: 11,
      change: 3,
      trend: 'up',
    },
    {
      rank: 8,
      learnerId: 'learner-020',
      learnerName: 'Riley Johnson',
      learnerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Riley',
      score: 2950,
      level: 10,
      change: -1,
      trend: 'down',
    },
    {
      rank: 9,
      learnerId: 'learner-018',
      learnerName: 'Quinn Anderson',
      learnerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Quinn',
      score: 2780,
      level: 10,
      change: 0,
      trend: 'same',
    },
    {
      rank: 10,
      learnerId: 'learner-025',
      learnerName: 'Avery Brown',
      learnerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Avery',
      score: 2650,
      level: 9,
      change: 4,
      trend: 'up',
    },
  ],
  lastUpdated: '2024-12-08T00:00:00Z',
};

export const mockRewards: Reward[] = [
  {
    id: 'reward-001',
    name: 'Amazon Gift Card ($10)',
    description: 'Redeem for a $10 Amazon gift card. Code delivered via email within 24 hours.',
    image: '/rewards/amazon-10.png',
    category: 'digital',
    pointsCost: 1000,
    stock: null,
    claimed: 2450,
    isActive: true,
    fulfillmentType: 'automatic',
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'reward-002',
    name: 'Extra Day Off',
    description: 'Earn an extra paid day off. Subject to manager approval.',
    image: '/rewards/day-off.png',
    category: 'experience',
    pointsCost: 5000,
    stock: 50,
    claimed: 23,
    isActive: true,
    minLevel: 5,
    fulfillmentType: 'manual',
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'reward-003',
    name: 'Company Swag Pack',
    description: 'Premium company merchandise including hoodie, t-shirt, and water bottle.',
    image: '/rewards/swag-pack.png',
    category: 'physical',
    pointsCost: 2500,
    stock: 100,
    claimed: 67,
    isActive: true,
    fulfillmentType: 'manual',
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'reward-004',
    name: 'Premium Course Access',
    description: 'Unlock access to a premium course of your choice (up to $200 value).',
    image: '/rewards/premium-course.png',
    category: 'course',
    pointsCost: 1500,
    stock: null,
    claimed: 890,
    isActive: true,
    fulfillmentType: 'automatic',
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

export const mockGamificationProfile: GamificationProfile = {
  learnerId: 'learner-001',
  level: 12,
  levelName: 'Achiever',
  xp: 4520,
  xpToNextLevel: 480,
  totalXp: 4520,
  points: 2340,
  totalPointsEarned: 3890,
  totalPointsSpent: 1550,
  currentStreak: 15,
  longestStreak: 32,
  freezesAvailable: 2,
  badgeCount: 12,
  badges: mockEarnedBadges,
  rank: 4,
  percentile: 92,
  leaderboardPosition: {
    leaderboardId: 'lb-global-monthly',
    rank: 4,
    score: 3720,
    change: 0,
    previousRank: 4,
  },
  recentXpGains: [
    {
      id: 'xp-001',
      amount: 150,
      source: 'course',
      sourceId: 'course-002',
      description: 'Lesson completed',
      earnedAt: '2024-12-08T10:30:00Z',
    },
    {
      id: 'xp-002',
      amount: 50,
      source: 'quiz',
      sourceId: 'quiz-001',
      description: 'Quiz passed',
      earnedAt: '2024-12-08T09:15:00Z',
    },
    {
      id: 'xp-003',
      amount: 25,
      source: 'streak',
      sourceId: 'streak-15',
      description: '15-day streak',
      earnedAt: '2024-12-08T00:00:00Z',
    },
  ],
  recentBadges: mockEarnedBadges.slice(0, 2),
};

// Helper functions
export function getBadgeById(id: string): Badge | undefined {
  return mockBadges.find((badge) => badge.id === id);
}

export function getBadgesByCategory(category: string): Badge[] {
  return mockBadges.filter((badge) => badge.category === category);
}

export function getEarnedBadgesForLearner(learnerId: string): EarnedBadge[] {
  return mockEarnedBadges.filter((eb) => eb.learnerId === learnerId);
}

export function getLevelForXp(xp: number): LevelDefinition {
  return (
    mockLevelDefinitions.find((level) => xp >= level.minXp && xp <= level.maxXp) ||
    mockLevelDefinitions[0]
  );
}
