/**
 * Mock course data for LXP360
 */

import type { Category, Course, CourseReview, INSPIREStage, Module } from '@/types/lms';
import { mockInstructors } from './users';

export const mockCategories: Category[] = [
  {
    id: 'cat-tech',
    name: 'Technology & Development',
    slug: 'technology-development',
    description: 'Software development, cloud computing, and technical skills',
    icon: 'Code',
    color: '#3B82F6',
    courseCount: 45,
  },
  {
    id: 'cat-leadership',
    name: 'Leadership & Management',
    slug: 'leadership-management',
    description: 'Leadership skills, team management, and executive development',
    icon: 'Users',
    color: '#8B5CF6',
    courseCount: 28,
  },
  {
    id: 'cat-compliance',
    name: 'Compliance & Safety',
    slug: 'compliance-safety',
    description: 'Regulatory compliance, workplace safety, and industry standards',
    icon: 'Shield',
    color: '#10B981',
    courseCount: 52,
  },
  {
    id: 'cat-healthcare',
    name: 'Healthcare',
    slug: 'healthcare',
    description: 'Healthcare compliance, clinical skills, and patient care',
    icon: 'Heart',
    color: '#EF4444',
    courseCount: 38,
  },
  {
    id: 'cat-soft-skills',
    name: 'Professional Skills',
    slug: 'professional-skills',
    description: 'Communication, productivity, and career development',
    icon: 'Lightbulb',
    color: '#F59E0B',
    courseCount: 32,
  },
  {
    id: 'cat-onboarding',
    name: 'Onboarding',
    slug: 'onboarding',
    description: 'New hire orientation and company training',
    icon: 'Rocket',
    color: '#EC4899',
    courseCount: 15,
  },
  {
    id: 'cat-manufacturing',
    name: 'Manufacturing & Industrial',
    slug: 'manufacturing-industrial',
    description: 'Manufacturing processes, quality control, and industrial safety',
    icon: 'Factory',
    color: '#6366F1',
    courseCount: 24,
  },
  {
    id: 'cat-aerospace',
    name: 'Aerospace & Defense',
    slug: 'aerospace-defense',
    description: 'Aviation training, ITAR compliance, and defense protocols',
    icon: 'Plane',
    color: '#0EA5E9',
    courseCount: 18,
  },
];

const createModules = (courseId: string, moduleCount: number): Module[] => {
  const inspireStages: INSPIREStage[] = [
    'ignite',
    'navigate',
    'scaffold',
    'practice',
    'integrate',
    'reflect',
    'extend',
  ];

  return Array.from({ length: moduleCount }, (_, i) => ({
    id: `${courseId}-module-${i + 1}`,
    courseId,
    title: `Module ${i + 1}: ${['Introduction', 'Core Concepts', 'Advanced Topics', 'Practical Application', 'Assessment'][i] || `Part ${i + 1}`}`,
    description: `Module ${i + 1} of this course covering key topics and concepts.`,
    order: i + 1,
    duration: Math.floor(Math.random() * 30) + 15,
    lessons: Array.from({ length: Math.floor(Math.random() * 4) + 3 }, (_, j) => ({
      id: `${courseId}-module-${i + 1}-lesson-${j + 1}`,
      moduleId: `${courseId}-module-${i + 1}`,
      title: `Lesson ${j + 1}`,
      description: `Lesson ${j + 1} content description`,
      order: j + 1,
      duration: Math.floor(Math.random() * 15) + 5,
      contentType: (['video', 'text', 'interactive', 'document'] as const)[
        Math.floor(Math.random() * 4)
      ],
      inspireStage: inspireStages[Math.min(i, inspireStages.length - 1)],
      cognitiveLoadTarget: (['low', 'medium', 'high'] as const)[Math.floor(Math.random() * 3)],
      isPreviewable: j === 0,
      isRequired: true,
      xpReward: 50,
      resources: [],
      hasTranscript: true,
      hasCaptions: true,
      hasAudioDescription: false,
    })),
    isLocked: i > 0,
    completionRequirement: 'all',
  }));
};

export const mockCourses: Course[] = [
  {
    id: 'course-001',
    title: 'JavaScript Fundamentals: From Zero to Hero',
    slug: 'javascript-fundamentals',
    description:
      'Master JavaScript from the ground up. This comprehensive course covers everything from basic syntax to advanced concepts like closures, prototypes, and async programming. Perfect for beginners looking to start their web development journey.',
    shortDescription: 'Complete JavaScript course for beginners to advanced developers',
    thumbnail: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=800',
    coverImage: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=1600',
    previewVideo: 'https://www.youtube.com/watch?v=example1',
    duration: 480,
    difficulty: 'beginner',
    category: mockCategories[0],
    tags: ['javascript', 'web development', 'programming', 'frontend'],
    skills: [
      { skillId: 'skill-js', skillName: 'JavaScript', levelGained: 30, category: 'Technical' },
      {
        skillId: 'skill-problem-solving',
        skillName: 'Problem Solving',
        levelGained: 15,
        category: 'Soft Skills',
      },
    ],
    modules: createModules('course-001', 5),
    instructor: mockInstructors[3],
    prerequisites: [],
    rating: 4.8,
    reviewCount: 1247,
    enrollmentCount: 15420,
    completionRate: 68,
    lessonCount: 42,
    quizCount: 8,
    isRequired: false,
    isFree: false,
    price: 199,
    salePrice: 49,
    currency: 'USD',
    inspireStages: ['ignite', 'navigate', 'scaffold', 'practice', 'integrate', 'reflect', 'extend'],
    cognitiveLoadTarget: 'medium',
    xpTotal: 2500,
    badgeIds: ['badge-js-fundamentals'],
    certificateTemplateId: 'cert-tech-001',
    language: 'en',
    captions: ['en', 'es', 'fr', 'de'],
    creditsOffered: 2,
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-11-20T10:30:00Z',
    publishedAt: '2024-02-01T08:00:00Z',
    status: 'published',
    version: '2.1',
    accessType: 'enrolled',
  },
  {
    id: 'course-002',
    title: 'React & Next.js: Building Modern Web Applications',
    slug: 'react-nextjs-modern-web',
    description:
      'Learn to build production-ready web applications with React and Next.js. Covers hooks, state management, server-side rendering, API routes, and deployment strategies.',
    shortDescription: 'Build modern web apps with React and Next.js',
    thumbnail: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800',
    coverImage: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=1600',
    duration: 720,
    difficulty: 'intermediate',
    category: mockCategories[0],
    tags: ['react', 'nextjs', 'web development', 'frontend', 'typescript'],
    skills: [
      { skillId: 'skill-react', skillName: 'React', levelGained: 40, category: 'Technical' },
      { skillId: 'skill-nextjs', skillName: 'Next.js', levelGained: 35, category: 'Technical' },
    ],
    modules: createModules('course-002', 6),
    instructor: mockInstructors[3],
    prerequisites: [
      { courseId: 'course-001', courseTitle: 'JavaScript Fundamentals', isRequired: true },
    ],
    rating: 4.9,
    reviewCount: 892,
    enrollmentCount: 8750,
    completionRate: 72,
    lessonCount: 56,
    quizCount: 10,
    isRequired: false,
    isFree: false,
    price: 249,
    currency: 'USD',
    inspireStages: ['ignite', 'navigate', 'scaffold', 'practice', 'integrate', 'reflect', 'extend'],
    cognitiveLoadTarget: 'medium',
    xpTotal: 3500,
    badgeIds: ['badge-react-developer'],
    certificateTemplateId: 'cert-tech-001',
    language: 'en',
    captions: ['en', 'es'],
    creditsOffered: 3,
    createdAt: '2024-03-01T08:00:00Z',
    updatedAt: '2024-11-15T14:20:00Z',
    publishedAt: '2024-03-15T08:00:00Z',
    status: 'published',
    version: '1.5',
    accessType: 'enrolled',
  },
  {
    id: 'course-003',
    title: 'HIPAA Compliance Fundamentals',
    slug: 'hipaa-compliance-fundamentals',
    description:
      'Essential HIPAA training for healthcare professionals. Learn about the Privacy Rule, Security Rule, and Breach Notification requirements. This course satisfies annual HIPAA training requirements.',
    shortDescription: 'Essential HIPAA compliance training for healthcare workers',
    thumbnail: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800',
    coverImage: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1600',
    duration: 90,
    difficulty: 'beginner',
    category: mockCategories[3],
    tags: ['hipaa', 'healthcare', 'compliance', 'privacy', 'security'],
    skills: [
      {
        skillId: 'skill-hipaa',
        skillName: 'HIPAA Compliance',
        levelGained: 50,
        category: 'Compliance',
      },
      {
        skillId: 'skill-privacy',
        skillName: 'Data Privacy',
        levelGained: 25,
        category: 'Compliance',
      },
    ],
    modules: createModules('course-003', 4),
    instructor: mockInstructors[2],
    prerequisites: [],
    rating: 4.7,
    reviewCount: 3420,
    enrollmentCount: 28340,
    completionRate: 94,
    lessonCount: 18,
    quizCount: 4,
    isRequired: true,
    complianceType: 'annual',
    complianceCode: 'HIPAA-101',
    regulatoryBody: 'HHS',
    recertificationPeriod: 365,
    isFree: true,
    currency: 'USD',
    inspireStages: ['ignite', 'navigate', 'scaffold', 'practice', 'integrate'],
    cognitiveLoadTarget: 'low',
    xpTotal: 500,
    badgeIds: ['badge-hipaa-certified'],
    certificateTemplateId: 'cert-compliance-001',
    language: 'en',
    captions: ['en', 'es'],
    ceuCredits: 1.5,
    createdAt: '2023-06-01T08:00:00Z',
    updatedAt: '2024-10-01T09:00:00Z',
    publishedAt: '2023-06-15T08:00:00Z',
    status: 'published',
    version: '3.0',
    accessType: 'enrolled',
  },
  {
    id: 'course-004',
    title: 'OSHA Workplace Safety Essentials',
    slug: 'osha-workplace-safety',
    description:
      'Comprehensive OSHA workplace safety training covering hazard identification, PPE requirements, emergency procedures, and regulatory compliance. Required for all manufacturing and industrial workers.',
    shortDescription: 'Essential OSHA safety training for workplace compliance',
    thumbnail: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800',
    coverImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1600',
    duration: 120,
    difficulty: 'beginner',
    category: mockCategories[2],
    tags: ['osha', 'safety', 'compliance', 'workplace', 'manufacturing'],
    skills: [
      {
        skillId: 'skill-osha',
        skillName: 'OSHA Compliance',
        levelGained: 50,
        category: 'Compliance',
      },
      {
        skillId: 'skill-safety',
        skillName: 'Workplace Safety',
        levelGained: 40,
        category: 'Safety',
      },
    ],
    modules: createModules('course-004', 5),
    instructor: mockInstructors[4],
    prerequisites: [],
    rating: 4.6,
    reviewCount: 5680,
    enrollmentCount: 45680,
    completionRate: 91,
    lessonCount: 24,
    quizCount: 5,
    isRequired: true,
    complianceType: 'annual',
    complianceCode: 'OSHA-10',
    regulatoryBody: 'OSHA',
    recertificationPeriod: 365,
    isFree: true,
    currency: 'USD',
    inspireStages: ['ignite', 'navigate', 'scaffold', 'practice', 'integrate'],
    cognitiveLoadTarget: 'low',
    xpTotal: 600,
    badgeIds: ['badge-osha-certified'],
    certificateTemplateId: 'cert-compliance-001',
    language: 'en',
    captions: ['en', 'es', 'zh'],
    ceuCredits: 2,
    createdAt: '2023-04-01T08:00:00Z',
    updatedAt: '2024-09-15T11:30:00Z',
    publishedAt: '2023-04-15T08:00:00Z',
    status: 'published',
    version: '2.5',
    accessType: 'enrolled',
  },
  {
    id: 'course-005',
    title: 'Leadership Excellence: The Complete Guide',
    slug: 'leadership-excellence-complete-guide',
    description:
      'Transform your leadership capabilities with this comprehensive program. Learn situational leadership, emotional intelligence, strategic thinking, and how to build high-performing teams.',
    shortDescription: 'Master essential leadership skills for career advancement',
    thumbnail: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800',
    coverImage: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1600',
    duration: 360,
    difficulty: 'intermediate',
    category: mockCategories[1],
    tags: ['leadership', 'management', 'soft skills', 'executive', 'team building'],
    skills: [
      {
        skillId: 'skill-leadership',
        skillName: 'Leadership',
        levelGained: 45,
        category: 'Leadership',
      },
      {
        skillId: 'skill-eq',
        skillName: 'Emotional Intelligence',
        levelGained: 30,
        category: 'Soft Skills',
      },
      {
        skillId: 'skill-strategy',
        skillName: 'Strategic Thinking',
        levelGained: 25,
        category: 'Business',
      },
    ],
    modules: createModules('course-005', 6),
    instructor: mockInstructors[1],
    prerequisites: [],
    rating: 4.9,
    reviewCount: 1850,
    enrollmentCount: 9850,
    completionRate: 76,
    lessonCount: 38,
    quizCount: 6,
    isRequired: false,
    isFree: false,
    price: 399,
    salePrice: 299,
    currency: 'USD',
    inspireStages: ['ignite', 'navigate', 'scaffold', 'practice', 'integrate', 'reflect', 'extend'],
    cognitiveLoadTarget: 'medium',
    xpTotal: 2000,
    badgeIds: ['badge-leader', 'badge-team-builder'],
    certificateTemplateId: 'cert-leadership-001',
    language: 'en',
    captions: ['en', 'es', 'fr'],
    creditsOffered: 4,
    createdAt: '2024-02-01T08:00:00Z',
    updatedAt: '2024-11-10T16:45:00Z',
    publishedAt: '2024-02-15T08:00:00Z',
    status: 'published',
    version: '1.2',
    accessType: 'enrolled',
  },
  {
    id: 'course-006',
    title: 'Data Analytics with Python',
    slug: 'data-analytics-python',
    description:
      'Learn data analysis using Python, pandas, and visualization libraries. From data cleaning to advanced statistical analysis and machine learning basics.',
    shortDescription: 'Master data analytics with Python and popular libraries',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
    coverImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1600',
    duration: 540,
    difficulty: 'intermediate',
    category: mockCategories[0],
    tags: ['python', 'data analytics', 'pandas', 'data science', 'visualization'],
    skills: [
      { skillId: 'skill-python', skillName: 'Python', levelGained: 35, category: 'Technical' },
      {
        skillId: 'skill-analytics',
        skillName: 'Data Analytics',
        levelGained: 45,
        category: 'Technical',
      },
    ],
    modules: createModules('course-006', 7),
    instructor: mockInstructors[0],
    prerequisites: [],
    rating: 4.8,
    reviewCount: 2156,
    enrollmentCount: 12340,
    completionRate: 65,
    lessonCount: 48,
    quizCount: 9,
    isRequired: false,
    isFree: false,
    price: 299,
    currency: 'USD',
    inspireStages: ['ignite', 'navigate', 'scaffold', 'practice', 'integrate', 'reflect', 'extend'],
    cognitiveLoadTarget: 'high',
    xpTotal: 3000,
    badgeIds: ['badge-data-analyst'],
    certificateTemplateId: 'cert-tech-001',
    language: 'en',
    captions: ['en'],
    creditsOffered: 3,
    createdAt: '2024-04-01T08:00:00Z',
    updatedAt: '2024-11-05T13:20:00Z',
    publishedAt: '2024-04-15T08:00:00Z',
    status: 'published',
    version: '1.3',
    accessType: 'enrolled',
  },
  {
    id: 'course-007',
    title: 'Cybersecurity Awareness for Employees',
    slug: 'cybersecurity-awareness',
    description:
      'Essential cybersecurity training for all employees. Learn to identify phishing attacks, protect sensitive data, and follow security best practices.',
    shortDescription: 'Protect yourself and your organization from cyber threats',
    thumbnail: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800',
    coverImage: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=1600',
    duration: 60,
    difficulty: 'beginner',
    category: mockCategories[2],
    tags: ['cybersecurity', 'security', 'compliance', 'phishing', 'data protection'],
    skills: [
      {
        skillId: 'skill-security',
        skillName: 'Security Awareness',
        levelGained: 40,
        category: 'Compliance',
      },
    ],
    modules: createModules('course-007', 3),
    instructor: mockInstructors[4],
    prerequisites: [],
    rating: 4.5,
    reviewCount: 8920,
    enrollmentCount: 52000,
    completionRate: 88,
    lessonCount: 12,
    quizCount: 3,
    isRequired: true,
    complianceType: 'annual',
    complianceCode: 'SEC-101',
    recertificationPeriod: 365,
    isFree: true,
    currency: 'USD',
    inspireStages: ['ignite', 'navigate', 'scaffold', 'practice'],
    cognitiveLoadTarget: 'low',
    xpTotal: 300,
    badgeIds: ['badge-security-aware'],
    certificateTemplateId: 'cert-compliance-001',
    language: 'en',
    captions: ['en', 'es', 'fr', 'de', 'pt'],
    ceuCredits: 1,
    createdAt: '2023-01-15T08:00:00Z',
    updatedAt: '2024-08-20T09:15:00Z',
    publishedAt: '2023-02-01T08:00:00Z',
    status: 'published',
    version: '4.0',
    accessType: 'enrolled',
  },
  {
    id: 'course-008',
    title: 'Effective Communication Skills',
    slug: 'effective-communication-skills',
    description:
      'Master the art of professional communication. Learn written, verbal, and presentation skills that will help you succeed in unknown role.',
    shortDescription: 'Improve your professional communication abilities',
    thumbnail: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800',
    coverImage: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=1600',
    duration: 180,
    difficulty: 'beginner',
    category: mockCategories[4],
    tags: ['communication', 'soft skills', 'presentation', 'writing', 'professional development'],
    skills: [
      {
        skillId: 'skill-communication',
        skillName: 'Communication',
        levelGained: 40,
        category: 'Soft Skills',
      },
      {
        skillId: 'skill-presentation',
        skillName: 'Presentation',
        levelGained: 30,
        category: 'Soft Skills',
      },
    ],
    modules: createModules('course-008', 4),
    instructor: mockInstructors[1],
    prerequisites: [],
    rating: 4.7,
    reviewCount: 2340,
    enrollmentCount: 18500,
    completionRate: 82,
    lessonCount: 20,
    quizCount: 4,
    isRequired: false,
    isFree: false,
    price: 149,
    salePrice: 99,
    currency: 'USD',
    inspireStages: ['ignite', 'navigate', 'scaffold', 'practice', 'integrate', 'reflect'],
    cognitiveLoadTarget: 'low',
    xpTotal: 1000,
    badgeIds: ['badge-communicator'],
    certificateTemplateId: 'cert-soft-skills-001',
    language: 'en',
    captions: ['en', 'es'],
    creditsOffered: 2,
    createdAt: '2023-08-01T08:00:00Z',
    updatedAt: '2024-07-15T11:00:00Z',
    publishedAt: '2023-08-15T08:00:00Z',
    status: 'published',
    version: '2.0',
    accessType: 'enrolled',
  },
  {
    id: 'course-009',
    title: 'Project Management Professional Prep',
    slug: 'pmp-prep-course',
    description:
      'Comprehensive PMP certification preparation course. Covers all knowledge areas and process groups based on the latest PMBOK Guide.',
    shortDescription: 'Prepare for the PMP certification exam',
    thumbnail: 'https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=800',
    coverImage: 'https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=1600',
    duration: 720,
    difficulty: 'advanced',
    category: mockCategories[1],
    tags: ['project management', 'pmp', 'certification', 'pmbok', 'agile'],
    skills: [
      {
        skillId: 'skill-pm-pro',
        skillName: 'Project Management',
        levelGained: 60,
        category: 'Business',
      },
      {
        skillId: 'skill-agile',
        skillName: 'Agile Methodologies',
        levelGained: 35,
        category: 'Business',
      },
    ],
    modules: createModules('course-009', 8),
    instructor: mockInstructors[1],
    prerequisites: [],
    rating: 4.9,
    reviewCount: 1567,
    enrollmentCount: 7890,
    completionRate: 58,
    lessonCount: 64,
    quizCount: 12,
    isRequired: false,
    isFree: false,
    price: 499,
    currency: 'USD',
    inspireStages: ['ignite', 'navigate', 'scaffold', 'practice', 'integrate', 'reflect', 'extend'],
    cognitiveLoadTarget: 'high',
    xpTotal: 4000,
    badgeIds: ['badge-pm-expert'],
    certificateTemplateId: 'cert-certification-001',
    language: 'en',
    captions: ['en'],
    creditsOffered: 35,
    ceuCredits: 35,
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-10-30T15:30:00Z',
    publishedAt: '2024-01-15T08:00:00Z',
    status: 'published',
    version: '1.1',
    accessType: 'enrolled',
  },
  {
    id: 'course-010',
    title: 'New Employee Onboarding',
    slug: 'new-employee-onboarding',
    description:
      'Welcome to the company! This onboarding course covers company culture, policies, tools, and everything you need to succeed in your new role.',
    shortDescription: 'Essential onboarding training for new hires',
    thumbnail: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=800',
    coverImage: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=1600',
    duration: 180,
    difficulty: 'beginner',
    category: mockCategories[5],
    tags: ['onboarding', 'new hire', 'company culture', 'policies'],
    skills: [
      {
        skillId: 'skill-company-knowledge',
        skillName: 'Company Knowledge',
        levelGained: 50,
        category: 'Business',
      },
    ],
    modules: createModules('course-010', 5),
    instructor: mockInstructors[0],
    prerequisites: [],
    rating: 4.6,
    reviewCount: 4520,
    enrollmentCount: 12000,
    completionRate: 95,
    lessonCount: 25,
    quizCount: 5,
    isRequired: true,
    complianceType: 'onboarding',
    complianceCode: 'ONB-001',
    isFree: true,
    currency: 'USD',
    inspireStages: ['ignite', 'navigate', 'scaffold', 'practice', 'integrate'],
    cognitiveLoadTarget: 'low',
    xpTotal: 800,
    badgeIds: ['badge-onboarded'],
    certificateTemplateId: 'cert-onboarding-001',
    language: 'en',
    captions: ['en', 'es', 'fr', 'de', 'zh', 'ja'],
    createdAt: '2023-03-01T08:00:00Z',
    updatedAt: '2024-11-01T10:00:00Z',
    publishedAt: '2023-03-15T08:00:00Z',
    status: 'published',
    version: '5.0',
    accessType: 'enrolled',
  },
];

export const mockCourseReviews: CourseReview[] = [
  {
    id: 'review-001',
    courseId: 'course-001',
    learnerId: 'learner-001',
    learnerName: 'John Smith',
    learnerAvatar: 'https://images.unsplash.com/photo-1599566150163-29194dcabd36?w=150',
    rating: 5,
    title: 'Best JavaScript course I have ever taken!',
    content:
      'This course exceeded all my expectations. The instructor explains complex concepts in a way that is easy to understand. The hands-on projects really helped solidify my learning.',
    helpful: 234,
    reported: false,
    createdAt: '2024-11-15T10:30:00Z',
    updatedAt: '2024-11-15T10:30:00Z',
  },
  {
    id: 'review-002',
    courseId: 'course-001',
    learnerId: 'learner-002',
    learnerName: 'Maria Garcia',
    learnerAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
    rating: 4,
    title: 'Great content, could use more exercises',
    content:
      'The course content is excellent and well-structured. I would have appreciated more practice exercises between lessons. Overall, highly recommended for beginners.',
    helpful: 89,
    reported: false,
    createdAt: '2024-11-10T14:20:00Z',
    updatedAt: '2024-11-10T14:20:00Z',
  },
];

// Helper functions
export function getCourseById(id: string): Course | undefined {
  return mockCourses.find((course) => course.id === id);
}

export function getCoursesByCategory(categoryId: string): Course[] {
  return mockCourses.filter((course) => course.category.id === categoryId);
}

export function getRequiredCourses(): Course[] {
  return mockCourses.filter((course) => course.isRequired);
}

export function getPopularCourses(limit: number = 10): Course[] {
  return [...mockCourses].sort((a, b) => b.enrollmentCount - a.enrollmentCount).slice(0, limit);
}

export function getNewCourses(limit: number = 10): Course[] {
  return [...mockCourses]
    .sort(
      (a, b) =>
        new Date(b.publishedAt || b.createdAt).getTime() -
        new Date(a.publishedAt || a.createdAt).getTime(),
    )
    .slice(0, limit);
}

export function searchCourses(query: string): Course[] {
  const searchTerm = query.toLowerCase();
  return mockCourses.filter(
    (course) =>
      course.title.toLowerCase().includes(searchTerm) ||
      course.description.toLowerCase().includes(searchTerm) ||
      course.tags.some((tag) => tag.toLowerCase().includes(searchTerm)),
  );
}
