/**
 * Mock discussions and Q&A data for LXP360
 */

import type {
  ActivityFeedItem,
  CommunityAnswer,
  CommunityQuestion,
  Discussion,
  DiscussionReply,
  ForumCategory,
} from '@/types/lms';

export const mockForumCategories: ForumCategory[] = [
  {
    id: 'forum-general',
    name: 'General Discussion',
    slug: 'general',
    description: 'General learning discussions and community conversations',
    icon: 'MessageSquare',
    color: '#3B82F6',
    order: 1,
    topicCount: 245,
    postCount: 1856,
    lastActivity: '2024-12-08T14:30:00Z',
    isPublic: true,
    requireApproval: false,
    moderators: ['admin-001'],
  },
  {
    id: 'forum-tech',
    name: 'Technology & Development',
    slug: 'technology',
    description: 'Programming, software development, and technical discussions',
    icon: 'Code',
    color: '#10B981',
    order: 2,
    topicCount: 456,
    postCount: 3245,
    lastActivity: '2024-12-08T15:20:00Z',
    isPublic: true,
    requireApproval: false,
    moderators: ['admin-001', 'instructor-001'],
  },
  {
    id: 'forum-leadership',
    name: 'Leadership & Management',
    slug: 'leadership',
    description: 'Leadership strategies, management techniques, and career growth',
    icon: 'Users',
    color: '#8B5CF6',
    order: 3,
    topicCount: 178,
    postCount: 1234,
    lastActivity: '2024-12-08T11:45:00Z',
    isPublic: true,
    requireApproval: false,
    moderators: ['admin-001', 'instructor-002'],
  },
  {
    id: 'forum-compliance',
    name: 'Compliance & Regulations',
    slug: 'compliance',
    description: 'Discussions about compliance training and regulatory requirements',
    icon: 'Shield',
    color: '#F59E0B',
    order: 4,
    topicCount: 89,
    postCount: 567,
    lastActivity: '2024-12-07T16:00:00Z',
    isPublic: true,
    requireApproval: true,
    moderators: ['admin-001', 'compliance-officer'],
  },
  {
    id: 'forum-career',
    name: 'Career Development',
    slug: 'career',
    description: 'Career advice, job hunting tips, and professional development',
    icon: 'TrendingUp',
    color: '#EC4899',
    order: 5,
    topicCount: 312,
    postCount: 2145,
    lastActivity: '2024-12-08T13:15:00Z',
    isPublic: true,
    requireApproval: false,
    moderators: ['admin-001'],
  },
];

export const mockDiscussions: Discussion[] = [
  {
    id: 'disc-001',
    categoryId: 'forum-tech',
    title: 'Best practices for React component architecture in large applications',
    body: 'I am working on a large-scale React application and looking for advice on organizing components. What patterns have worked best for you in terms of folder structure, state management, and reusability?',
    bodyHtml:
      '<p>I am working on a large-scale React application and looking for advice on organizing components. What patterns have worked best for you in terms of folder structure, state management, and reusability?</p>',
    attachments: [],
    authorId: 'learner-001',
    authorName: 'John Smith',
    authorAvatar: 'https://images.unsplash.com/photo-1599566150163-29194dcabd36?w=150',
    authorRole: 'Software Engineer',
    status: 'open',
    moderationStatus: 'approved',
    isPinned: false,
    isAnnouncement: false,
    isFeatured: true,
    views: 1245,
    replyCount: 23,
    upvotes: 45,
    downvotes: 2,
    score: 43,
    isQuestion: false,
    isAnswered: false,
    tags: ['react', 'architecture', 'best-practices'],
    createdAt: '2024-11-15T10:30:00Z',
    updatedAt: '2024-12-08T09:15:00Z',
    lastReplyAt: '2024-12-08T09:15:00Z',
    participants: ['learner-001', 'learner-005', 'learner-012', 'inst-004'],
    participantCount: 15,
    subscriberCount: 28,
  },
  {
    id: 'disc-002',
    categoryId: 'forum-leadership',
    courseId: 'course-005',
    title: 'How do you handle difficult conversations with team members?',
    body: 'One of the most challenging aspects of leadership is having difficult conversations. I am curious about strategies others have found effective for addressing performance issues while maintaining positive relationships.',
    bodyHtml:
      "<p>One of the most challenging aspects of leadership is having difficult conversations. I'm curious about strategies others have found effective for addressing performance issues while maintaining positive relationships.</p>",
    attachments: [],
    authorId: 'learner-002',
    authorName: 'Maria Garcia',
    authorAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
    authorRole: 'Product Manager',
    status: 'open',
    moderationStatus: 'approved',
    isPinned: true,
    isAnnouncement: false,
    isFeatured: false,
    views: 892,
    replyCount: 18,
    upvotes: 67,
    downvotes: 1,
    score: 66,
    isQuestion: true,
    isAnswered: true,
    acceptedAnswerId: 'reply-002',
    tags: ['leadership', 'communication', 'management'],
    createdAt: '2024-11-20T14:00:00Z',
    updatedAt: '2024-12-07T16:30:00Z',
    lastReplyAt: '2024-12-07T16:30:00Z',
    participants: ['learner-002', 'learner-010', 'inst-001'],
    participantCount: 12,
    subscriberCount: 45,
  },
  {
    id: 'disc-003',
    categoryId: 'forum-general',
    title: 'Study group for PMP certification - Who is interested?',
    body: 'I am preparing for the PMP exam and looking for study partners. Would anyone be interested in forming a virtual study group? We could meet weekly to discuss topics and quiz each other.',
    bodyHtml:
      "<p>I'm preparing for the PMP exam and looking for study partners. Would anyone be interested in forming a virtual study group? We could meet weekly to discuss topics and quiz each other.</p>",
    attachments: [],
    authorId: 'learner-008',
    authorName: 'Morgan Davis',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Morgan',
    authorRole: 'Project Coordinator',
    status: 'open',
    moderationStatus: 'approved',
    isPinned: false,
    isAnnouncement: false,
    isFeatured: false,
    views: 567,
    replyCount: 32,
    upvotes: 28,
    downvotes: 0,
    score: 28,
    isQuestion: false,
    isAnswered: false,
    tags: ['pmp', 'study-group', 'certification'],
    createdAt: '2024-12-01T09:00:00Z',
    updatedAt: '2024-12-08T11:30:00Z',
    lastReplyAt: '2024-12-08T11:30:00Z',
    participants: ['learner-008', 'learner-015', 'learner-020', 'learner-025'],
    participantCount: 18,
    subscriberCount: 22,
  },
];

export const mockDiscussionReplies: DiscussionReply[] = [
  {
    id: 'reply-001',
    discussionId: 'disc-001',
    body: 'Great question! I have found that using a feature-based folder structure works really well for large apps. Group components, hooks, and utilities by feature rather than by type. This makes it easier to understand and maintain related code.',
    bodyHtml:
      "<p>Great question! I've found that using a feature-based folder structure works really well for large apps. Group components, hooks, and utilities by feature rather than by type. This makes it easier to understand and maintain related code.</p>",
    attachments: [],
    authorId: 'inst-004',
    authorName: 'James Wilson',
    authorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    authorRole: 'Senior Technical Trainer',
    isInstructor: true,
    moderationStatus: 'approved',
    isAcceptedAnswer: false,
    isEdited: false,
    upvotes: 24,
    downvotes: 0,
    score: 24,
    replyCount: 3,
    createdAt: '2024-11-15T14:20:00Z',
    updatedAt: '2024-11-15T14:20:00Z',
  },
  {
    id: 'reply-002',
    discussionId: 'disc-002',
    body: 'The key is preparation and empathy. Before the conversation, document specific examples and focus on behaviors, not personality. During the conversation, listen actively, ask open-ended questions, and collaborate on solutions. Follow up with a written summary and clear next steps.',
    bodyHtml:
      '<p>The key is preparation and empathy. Before the conversation, document specific examples and focus on behaviors, not personality. During the conversation, listen actively, ask open-ended questions, and collaborate on solutions. Follow up with a written summary and clear next steps.</p>',
    attachments: [],
    authorId: 'inst-001',
    authorName: 'Marcus Johnson',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    authorRole: 'Leadership Development Expert',
    isInstructor: true,
    moderationStatus: 'approved',
    isAcceptedAnswer: true,
    isEdited: false,
    upvotes: 42,
    downvotes: 0,
    score: 42,
    replyCount: 5,
    createdAt: '2024-11-21T09:30:00Z',
    updatedAt: '2024-11-21T09:30:00Z',
  },
];

export const mockQuestions: CommunityQuestion[] = [
  {
    id: 'q-001',
    title: 'How do I implement authentication in Next.js 14 with server components?',
    body: 'I am building an app with Next.js 14 and want to implement authentication. What is the recommended approach with the new App Router and server components?',
    bodyHtml:
      "<p>I'm building an app with Next.js 14 and want to implement authentication. What is the recommended approach with the new App Router and server components?</p>",
    authorId: 'learner-012',
    authorName: 'Taylor Martinez',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Taylor',
    tags: ['nextjs', 'authentication', 'react'],
    skillIds: ['skill-nextjs', 'skill-react'],
    status: 'answered',
    acceptedAnswerId: 'a-001',
    views: 2456,
    upvotes: 89,
    downvotes: 2,
    score: 87,
    answerCount: 5,
    createdAt: '2024-11-10T08:00:00Z',
    updatedAt: '2024-11-12T15:30:00Z',
    answeredAt: '2024-11-11T10:00:00Z',
  },
  {
    id: 'q-002',
    title: 'What is the difference between HIPAA Privacy Rule and Security Rule?',
    body: 'I am studying for HIPAA certification and am confused about the distinction between the Privacy Rule and Security Rule. Can someone explain the key differences?',
    bodyHtml:
      "<p>I'm studying for HIPAA certification and am confused about the distinction between the Privacy Rule and Security Rule. Can someone explain the key differences?</p>",
    authorId: 'learner-020',
    authorName: 'Riley Johnson',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Riley',
    tags: ['hipaa', 'compliance', 'healthcare'],
    skillIds: ['skill-hipaa'],
    courseId: 'course-003',
    status: 'answered',
    acceptedAnswerId: 'a-002',
    views: 1234,
    upvotes: 45,
    downvotes: 0,
    score: 45,
    answerCount: 3,
    createdAt: '2024-12-01T11:00:00Z',
    updatedAt: '2024-12-02T14:00:00Z',
    answeredAt: '2024-12-01T16:30:00Z',
  },
  {
    id: 'q-003',
    title: 'Best resources for learning Python for data science?',
    body: 'I want to transition into data science and need to learn Python. What courses or resources would you recommend for someone with basic programming experience?',
    bodyHtml:
      '<p>I want to transition into data science and need to learn Python. What courses or resources would you recommend for someone with basic programming experience?</p>',
    authorId: 'learner-025',
    authorName: 'Avery Brown',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Avery',
    tags: ['python', 'data-science', 'learning'],
    skillIds: ['skill-python', 'skill-analytics'],
    status: 'open',
    views: 567,
    upvotes: 23,
    downvotes: 0,
    score: 23,
    answerCount: 8,
    createdAt: '2024-12-05T09:30:00Z',
    updatedAt: '2024-12-08T10:00:00Z',
  },
];

export const mockAnswers: CommunityAnswer[] = [
  {
    id: 'a-001',
    questionId: 'q-001',
    body: 'For Next.js 14 with App Router, I recommend using NextAuth.js (Auth.js) v5. It has first-class support for server components. Here is how to set it up:\n\n1. Install auth.js\n2. Create an auth.ts configuration file\n3. Set up middleware for protected routes\n4. Use the session in server components with auth()\n\nFor client components, use the SessionProvider and useSession hook.',
    bodyHtml:
      '<p>For Next.js 14 with App Router, I recommend using NextAuth.js (Auth.js) v5. It has first-class support for server components.</p>',
    authorId: 'inst-004',
    authorName: 'James Wilson',
    authorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    isExpert: true,
    isAccepted: true,
    upvotes: 67,
    downvotes: 1,
    score: 66,
    createdAt: '2024-11-11T10:00:00Z',
    updatedAt: '2024-11-11T10:00:00Z',
  },
  {
    id: 'a-002',
    questionId: 'q-002',
    body: 'Great question! The key difference is:\n\n**Privacy Rule**: Governs who can access Protected Health Information (PHI) and when. It covers use and disclosure of PHI.\n\n**Security Rule**: Focuses on HOW to protect electronic PHI (ePHI). It covers administrative, physical, and technical safeguards.\n\nThink of Privacy as the "what" and Security as the "how".',
    bodyHtml:
      '<p>Great question! The key difference is:</p><p><strong>Privacy Rule</strong>: Governs who can access Protected Health Information (PHI) and when.</p><p><strong>Security Rule</strong>: Focuses on HOW to protect electronic PHI (ePHI).</p>',
    authorId: 'inst-002',
    authorName: 'Dr. Emily Rodriguez',
    authorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    isExpert: true,
    isAccepted: true,
    upvotes: 38,
    downvotes: 0,
    score: 38,
    createdAt: '2024-12-01T16:30:00Z',
    updatedAt: '2024-12-01T16:30:00Z',
  },
];

export const mockActivityFeed: ActivityFeedItem[] = [
  {
    id: 'activity-001',
    type: 'course_completed',
    actorId: 'learner-010',
    actorName: 'Alex Thompson',
    actorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    action: 'completed',
    objectType: 'course',
    objectId: 'course-002',
    objectTitle: 'React & Next.js: Building Modern Web Applications',
    objectUrl: '/lms/course/course-002',
    createdAt: '2024-12-08T14:00:00Z',
  },
  {
    id: 'activity-002',
    type: 'badge_earned',
    actorId: 'learner-005',
    actorName: 'Jordan Chen',
    actorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan',
    action: 'earned',
    objectType: 'badge',
    objectId: 'badge-streak-30',
    objectTitle: 'Monthly Master',
    metadata: { rarity: 'rare' },
    createdAt: '2024-12-08T12:30:00Z',
  },
  {
    id: 'activity-003',
    type: 'level_up',
    actorId: 'learner-012',
    actorName: 'Taylor Martinez',
    actorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Taylor',
    action: 'reached',
    objectType: 'level',
    objectId: 'level-15',
    objectTitle: 'Level 15',
    metadata: { levelName: 'Expert', previousLevel: 14 },
    createdAt: '2024-12-08T11:00:00Z',
  },
  {
    id: 'activity-004',
    type: 'question_asked',
    actorId: 'learner-025',
    actorName: 'Avery Brown',
    actorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Avery',
    action: 'asked',
    objectType: 'question',
    objectId: 'q-003',
    objectTitle: 'Best resources for learning Python for data science?',
    objectUrl: '/lms/community/questions/q-003',
    createdAt: '2024-12-08T09:30:00Z',
  },
  {
    id: 'activity-005',
    type: 'certificate_earned',
    actorId: 'learner-001',
    actorName: 'John Smith',
    actorAvatar: 'https://images.unsplash.com/photo-1599566150163-29194dcabd36?w=150',
    action: 'earned',
    objectType: 'certificate',
    objectId: 'cert-002',
    objectTitle: 'HIPAA Compliance Certification',
    courseId: 'course-003',
    createdAt: '2024-12-08T08:00:00Z',
  },
  {
    id: 'activity-006',
    type: 'group_joined',
    actorId: 'learner-015',
    actorName: 'Casey Williams',
    actorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Casey',
    action: 'joined',
    objectType: 'group',
    objectId: 'group-pmp-study',
    objectTitle: 'PMP Certification Study Group',
    objectUrl: '/lms/community/groups/group-pmp-study',
    createdAt: '2024-12-07T16:00:00Z',
  },
];

// Helper functions
export function getDiscussionsByCategory(categoryId: string): Discussion[] {
  return mockDiscussions.filter((d) => d.categoryId === categoryId);
}

export function getDiscussionsByCourse(courseId: string): Discussion[] {
  return mockDiscussions.filter((d) => d.courseId === courseId);
}

export function getRepliesForDiscussion(discussionId: string): DiscussionReply[] {
  return mockDiscussionReplies.filter((r) => r.discussionId === discussionId);
}

export function getRecentQuestions(limit: number = 10): CommunityQuestion[] {
  return [...mockQuestions]
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
    .slice(0, limit);
}

export function getAnswersForQuestion(questionId: string): CommunityAnswer[] {
  return mockAnswers.filter((a) => a.questionId === questionId);
}
