/**
 * Mock learning path data for LXP360
 */

import type { LearningPath, LearningPathEnrollment } from '@/types/lms';

export const mockLearningPaths: LearningPath[] = [
  {
    id: 'path-001',
    title: 'Full-Stack Web Developer',
    slug: 'full-stack-web-developer',
    description:
      'Become a complete full-stack developer with this comprehensive learning path. Master frontend and backend technologies, databases, and deployment strategies. By the end, you will be able to build and deploy production-ready web applications.',
    shortDescription: 'Master web development from frontend to backend',
    thumbnail: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800',
    coverImage: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1600',
    stages: [
      {
        id: 'path-001-stage-1',
        title: 'Foundation',
        description: 'Build your programming foundation',
        order: 1,
        items: [
          {
            id: 'item-1',
            type: 'course',
            resourceId: 'course-001',
            title: 'JavaScript Fundamentals',
            duration: 480,
            order: 1,
            isRequired: true,
          },
        ],
      },
      {
        id: 'path-001-stage-2',
        title: 'Frontend Development',
        description: 'Learn modern frontend frameworks',
        order: 2,
        items: [
          {
            id: 'item-2',
            type: 'course',
            resourceId: 'course-002',
            title: 'React & Next.js',
            duration: 720,
            order: 1,
            isRequired: true,
          },
        ],
        unlockCriteria: { type: 'previous-stage', value: 'path-001-stage-1' },
      },
      {
        id: 'path-001-stage-3',
        title: 'Backend Development',
        description: 'Master server-side programming',
        order: 3,
        items: [
          {
            id: 'item-3',
            type: 'course',
            resourceId: 'course-backend',
            title: 'Node.js & APIs',
            duration: 540,
            order: 1,
            isRequired: true,
          },
          {
            id: 'item-4',
            type: 'course',
            resourceId: 'course-database',
            title: 'Database Design',
            duration: 360,
            order: 2,
            isRequired: true,
          },
        ],
        unlockCriteria: { type: 'previous-stage', value: 'path-001-stage-2' },
      },
      {
        id: 'path-001-stage-4',
        title: 'Capstone Project',
        description: 'Build a complete application',
        order: 4,
        items: [
          {
            id: 'item-5',
            type: 'milestone',
            resourceId: 'capstone-001',
            title: 'Full-Stack Project',
            description: 'Build and deploy a complete web application',
            duration: 1200,
            order: 1,
            isRequired: true,
          },
        ],
        unlockCriteria: { type: 'previous-stage', value: 'path-001-stage-3' },
      },
    ],
    totalCourses: 5,
    totalDuration: 3300,
    estimatedWeeks: 16,
    skills: [
      {
        skillId: 'skill-js',
        skillName: 'JavaScript',
        levelBefore: 0,
        levelAfter: 75,
        levelGain: 75,
      },
      { skillId: 'skill-react', skillName: 'React', levelBefore: 0, levelAfter: 70, levelGain: 70 },
      {
        skillId: 'skill-nodejs',
        skillName: 'Node.js',
        levelBefore: 0,
        levelAfter: 65,
        levelGain: 65,
      },
      { skillId: 'skill-sql', skillName: 'SQL', levelBefore: 0, levelAfter: 55, levelGain: 55 },
    ],
    badgeId: 'badge-fullstack-developer',
    roleTarget: 'Full-Stack Developer',
    enrollmentCount: 3420,
    completionRate: 45,
    rating: 4.8,
    reviewCount: 567,
    difficulty: 'intermediate',
    prerequisites: [],
    isRequired: false,
    isSequential: true,
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-11-01T10:00:00Z',
    publishedAt: '2024-01-15T08:00:00Z',
    status: 'published',
  },
  {
    id: 'path-002',
    title: 'Leadership Development Program',
    slug: 'leadership-development-program',
    description:
      'Develop the skills needed to lead teams and drive organizational success. This comprehensive program covers leadership fundamentals, emotional intelligence, strategic thinking, and change management.',
    shortDescription: 'Become an effective leader and team manager',
    thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800',
    coverImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1600',
    stages: [
      {
        id: 'path-002-stage-1',
        title: 'Leadership Foundations',
        description: 'Understanding leadership principles',
        order: 1,
        items: [
          {
            id: 'item-1',
            type: 'course',
            resourceId: 'course-005',
            title: 'Leadership Excellence',
            duration: 360,
            order: 1,
            isRequired: true,
          },
        ],
      },
      {
        id: 'path-002-stage-2',
        title: 'Communication & Influence',
        description: 'Master communication skills',
        order: 2,
        items: [
          {
            id: 'item-2',
            type: 'course',
            resourceId: 'course-008',
            title: 'Effective Communication',
            duration: 180,
            order: 1,
            isRequired: true,
          },
        ],
        unlockCriteria: { type: 'previous-stage', value: 'path-002-stage-1' },
      },
      {
        id: 'path-002-stage-3',
        title: 'Strategic Management',
        description: 'Learn to think strategically',
        order: 3,
        items: [
          {
            id: 'item-3',
            type: 'course',
            resourceId: 'course-strategy',
            title: 'Strategic Thinking',
            duration: 240,
            order: 1,
            isRequired: true,
          },
          {
            id: 'item-4',
            type: 'assessment',
            resourceId: 'assessment-leadership',
            title: 'Leadership Assessment',
            duration: 60,
            order: 2,
            isRequired: true,
          },
        ],
        unlockCriteria: { type: 'previous-stage', value: 'path-002-stage-2' },
      },
    ],
    totalCourses: 4,
    totalDuration: 840,
    estimatedWeeks: 8,
    skills: [
      {
        skillId: 'skill-leadership',
        skillName: 'Leadership',
        levelBefore: 20,
        levelAfter: 75,
        levelGain: 55,
      },
      {
        skillId: 'skill-communication',
        skillName: 'Communication',
        levelBefore: 30,
        levelAfter: 70,
        levelGain: 40,
      },
      {
        skillId: 'skill-strategy',
        skillName: 'Strategic Thinking',
        levelBefore: 15,
        levelAfter: 60,
        levelGain: 45,
      },
    ],
    badgeId: 'badge-emerging-leader',
    roleTarget: 'Team Lead / Manager',
    enrollmentCount: 2150,
    completionRate: 62,
    rating: 4.9,
    reviewCount: 423,
    difficulty: 'intermediate',
    prerequisites: [],
    isRequired: false,
    isSequential: true,
    createdAt: '2024-02-01T08:00:00Z',
    updatedAt: '2024-10-15T14:00:00Z',
    publishedAt: '2024-02-15T08:00:00Z',
    status: 'published',
  },
  {
    id: 'path-003',
    title: 'Data Science Fundamentals',
    slug: 'data-science-fundamentals',
    description:
      'Start your data science journey with this comprehensive learning path. Learn Python programming, statistics, data visualization, and machine learning basics.',
    shortDescription: 'Build foundational data science skills',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
    coverImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1600',
    stages: [
      {
        id: 'path-003-stage-1',
        title: 'Python Programming',
        description: 'Learn Python for data science',
        order: 1,
        items: [
          {
            id: 'item-1',
            type: 'course',
            resourceId: 'course-006',
            title: 'Data Analytics with Python',
            duration: 540,
            order: 1,
            isRequired: true,
          },
        ],
      },
      {
        id: 'path-003-stage-2',
        title: 'Statistics & Visualization',
        description: 'Statistical analysis and data viz',
        order: 2,
        items: [
          {
            id: 'item-2',
            type: 'course',
            resourceId: 'course-statistics',
            title: 'Statistics for Data Science',
            duration: 360,
            order: 1,
            isRequired: true,
          },
          {
            id: 'item-3',
            type: 'course',
            resourceId: 'course-viz',
            title: 'Data Visualization',
            duration: 240,
            order: 2,
            isRequired: true,
          },
        ],
        unlockCriteria: { type: 'previous-stage', value: 'path-003-stage-1' },
      },
      {
        id: 'path-003-stage-3',
        title: 'Machine Learning Intro',
        description: 'Introduction to ML concepts',
        order: 3,
        items: [
          {
            id: 'item-4',
            type: 'course',
            resourceId: 'course-ml-intro',
            title: 'Machine Learning Basics',
            duration: 480,
            order: 1,
            isRequired: true,
          },
        ],
        unlockCriteria: { type: 'previous-stage', value: 'path-003-stage-2' },
      },
    ],
    totalCourses: 4,
    totalDuration: 1620,
    estimatedWeeks: 12,
    skills: [
      {
        skillId: 'skill-python',
        skillName: 'Python',
        levelBefore: 0,
        levelAfter: 65,
        levelGain: 65,
      },
      {
        skillId: 'skill-analytics',
        skillName: 'Data Analytics',
        levelBefore: 0,
        levelAfter: 70,
        levelGain: 70,
      },
      {
        skillId: 'skill-ml',
        skillName: 'Machine Learning',
        levelBefore: 0,
        levelAfter: 45,
        levelGain: 45,
      },
    ],
    badgeId: 'badge-data-scientist',
    roleTarget: 'Data Analyst / Junior Data Scientist',
    enrollmentCount: 4560,
    completionRate: 52,
    rating: 4.7,
    reviewCount: 712,
    difficulty: 'intermediate',
    prerequisites: [],
    isRequired: false,
    isSequential: true,
    createdAt: '2024-03-01T08:00:00Z',
    updatedAt: '2024-11-05T09:30:00Z',
    publishedAt: '2024-03-15T08:00:00Z',
    status: 'published',
  },
  {
    id: 'path-004',
    title: 'Healthcare Compliance Certification',
    slug: 'healthcare-compliance-certification',
    description:
      'Complete all required healthcare compliance training including HIPAA, patient safety, and healthcare privacy regulations. Required for all healthcare workers.',
    shortDescription: 'Essential compliance training for healthcare professionals',
    thumbnail: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800',
    coverImage: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1600',
    stages: [
      {
        id: 'path-004-stage-1',
        title: 'HIPAA Training',
        description: 'Privacy and security fundamentals',
        order: 1,
        items: [
          {
            id: 'item-1',
            type: 'course',
            resourceId: 'course-003',
            title: 'HIPAA Compliance Fundamentals',
            duration: 90,
            order: 1,
            isRequired: true,
          },
        ],
      },
      {
        id: 'path-004-stage-2',
        title: 'Patient Safety',
        description: 'Patient safety protocols',
        order: 2,
        items: [
          {
            id: 'item-2',
            type: 'course',
            resourceId: 'course-patient-safety',
            title: 'Patient Safety Essentials',
            duration: 60,
            order: 1,
            isRequired: true,
          },
        ],
      },
      {
        id: 'path-004-stage-3',
        title: 'Healthcare Ethics',
        description: 'Ethics in healthcare',
        order: 3,
        items: [
          {
            id: 'item-3',
            type: 'course',
            resourceId: 'course-ethics',
            title: 'Healthcare Ethics',
            duration: 45,
            order: 1,
            isRequired: true,
          },
        ],
      },
    ],
    totalCourses: 3,
    totalDuration: 195,
    estimatedWeeks: 2,
    skills: [
      {
        skillId: 'skill-hipaa',
        skillName: 'HIPAA Compliance',
        levelBefore: 0,
        levelAfter: 80,
        levelGain: 80,
      },
      {
        skillId: 'skill-patient-safety',
        skillName: 'Patient Safety',
        levelBefore: 0,
        levelAfter: 70,
        levelGain: 70,
      },
    ],
    certificationId: 'cert-healthcare-001',
    badgeId: 'badge-healthcare-certified',
    roleTarget: 'Healthcare Professional',
    enrollmentCount: 12500,
    completionRate: 92,
    rating: 4.6,
    reviewCount: 2340,
    difficulty: 'beginner',
    prerequisites: [],
    isRequired: true,
    isSequential: false,
    createdAt: '2023-06-01T08:00:00Z',
    updatedAt: '2024-09-01T11:00:00Z',
    publishedAt: '2023-06-15T08:00:00Z',
    status: 'published',
  },
  {
    id: 'path-005',
    title: 'New Employee Onboarding',
    slug: 'new-employee-onboarding-path',
    description:
      'Complete onboarding path for new employees. Covers company culture, policies, tools, compliance basics, and role-specific training.',
    shortDescription: 'Get started at your new company',
    thumbnail: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=800',
    coverImage: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=1600',
    stages: [
      {
        id: 'path-005-stage-1',
        title: 'Welcome & Culture',
        description: 'Learn about our company',
        order: 1,
        items: [
          {
            id: 'item-1',
            type: 'course',
            resourceId: 'course-010',
            title: 'New Employee Onboarding',
            duration: 180,
            order: 1,
            isRequired: true,
          },
        ],
      },
      {
        id: 'path-005-stage-2',
        title: 'Security & Compliance',
        description: 'Essential security training',
        order: 2,
        items: [
          {
            id: 'item-2',
            type: 'course',
            resourceId: 'course-007',
            title: 'Cybersecurity Awareness',
            duration: 60,
            order: 1,
            isRequired: true,
          },
        ],
      },
      {
        id: 'path-005-stage-3',
        title: 'Tools & Systems',
        description: 'Learn our tools',
        order: 3,
        items: [
          {
            id: 'item-3',
            type: 'course',
            resourceId: 'course-tools',
            title: 'Company Tools Training',
            duration: 120,
            order: 1,
            isRequired: true,
          },
        ],
      },
    ],
    totalCourses: 3,
    totalDuration: 360,
    estimatedWeeks: 1,
    skills: [
      {
        skillId: 'skill-company-knowledge',
        skillName: 'Company Knowledge',
        levelBefore: 0,
        levelAfter: 80,
        levelGain: 80,
      },
      {
        skillId: 'skill-security',
        skillName: 'Security Awareness',
        levelBefore: 0,
        levelAfter: 60,
        levelGain: 60,
      },
    ],
    badgeId: 'badge-onboarded',
    roleTarget: 'New Employee',
    enrollmentCount: 8500,
    completionRate: 98,
    rating: 4.5,
    reviewCount: 1890,
    difficulty: 'beginner',
    prerequisites: [],
    isRequired: true,
    isSequential: true,
    createdAt: '2023-01-01T08:00:00Z',
    updatedAt: '2024-11-01T08:00:00Z',
    publishedAt: '2023-01-15T08:00:00Z',
    status: 'published',
  },
  {
    id: 'path-006',
    title: 'Project Management Professional (PMP) Track',
    slug: 'pmp-certification-track',
    description:
      'Prepare for the PMP certification exam with this comprehensive learning path. Covers all PMBOK Guide knowledge areas and includes practice exams.',
    shortDescription: 'Complete PMP certification preparation',
    thumbnail: 'https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=800',
    coverImage: 'https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=1600',
    stages: [
      {
        id: 'path-006-stage-1',
        title: 'PM Fundamentals',
        description: 'Project management basics',
        order: 1,
        items: [
          {
            id: 'item-1',
            type: 'course',
            resourceId: 'course-pm-basics',
            title: 'PM Fundamentals',
            duration: 240,
            order: 1,
            isRequired: true,
          },
        ],
      },
      {
        id: 'path-006-stage-2',
        title: 'PMP Exam Prep',
        description: 'Comprehensive exam preparation',
        order: 2,
        items: [
          {
            id: 'item-2',
            type: 'course',
            resourceId: 'course-009',
            title: 'PMP Professional Prep',
            duration: 720,
            order: 1,
            isRequired: true,
          },
        ],
        unlockCriteria: { type: 'previous-stage', value: 'path-006-stage-1' },
      },
      {
        id: 'path-006-stage-3',
        title: 'Practice Exams',
        description: 'Test your knowledge',
        order: 3,
        items: [
          {
            id: 'item-3',
            type: 'assessment',
            resourceId: 'exam-pmp-practice-1',
            title: 'PMP Practice Exam 1',
            duration: 240,
            order: 1,
            isRequired: true,
          },
          {
            id: 'item-4',
            type: 'assessment',
            resourceId: 'exam-pmp-practice-2',
            title: 'PMP Practice Exam 2',
            duration: 240,
            order: 2,
            isRequired: true,
          },
        ],
        unlockCriteria: { type: 'previous-stage', value: 'path-006-stage-2' },
      },
    ],
    totalCourses: 3,
    totalDuration: 1440,
    estimatedWeeks: 10,
    skills: [
      {
        skillId: 'skill-pm-pro',
        skillName: 'Project Management',
        levelBefore: 30,
        levelAfter: 90,
        levelGain: 60,
      },
      {
        skillId: 'skill-agile',
        skillName: 'Agile Methodologies',
        levelBefore: 20,
        levelAfter: 70,
        levelGain: 50,
      },
    ],
    certificationId: 'cert-pmp',
    badgeId: 'badge-pmp-ready',
    roleTarget: 'Project Manager',
    enrollmentCount: 5670,
    completionRate: 55,
    rating: 4.9,
    reviewCount: 1123,
    difficulty: 'advanced',
    prerequisites: [],
    isRequired: false,
    isSequential: true,
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-10-20T15:00:00Z',
    publishedAt: '2024-01-15T08:00:00Z',
    status: 'published',
  },
  {
    id: 'path-007',
    title: 'Manufacturing Safety Certification',
    slug: 'manufacturing-safety-certification',
    description:
      'Complete safety certification for manufacturing workers. Covers OSHA regulations, equipment safety, hazard identification, and emergency procedures.',
    shortDescription: 'Essential safety training for manufacturing',
    thumbnail: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800',
    coverImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1600',
    stages: [
      {
        id: 'path-007-stage-1',
        title: 'OSHA Fundamentals',
        description: 'Core OSHA requirements',
        order: 1,
        items: [
          {
            id: 'item-1',
            type: 'course',
            resourceId: 'course-004',
            title: 'OSHA Workplace Safety',
            duration: 120,
            order: 1,
            isRequired: true,
          },
        ],
      },
      {
        id: 'path-007-stage-2',
        title: 'Equipment Safety',
        description: 'Safe equipment operation',
        order: 2,
        items: [
          {
            id: 'item-2',
            type: 'course',
            resourceId: 'course-equipment',
            title: 'Equipment Safety Training',
            duration: 90,
            order: 1,
            isRequired: true,
          },
        ],
      },
      {
        id: 'path-007-stage-3',
        title: 'Emergency Response',
        description: 'Emergency procedures',
        order: 3,
        items: [
          {
            id: 'item-3',
            type: 'course',
            resourceId: 'course-emergency',
            title: 'Emergency Response',
            duration: 60,
            order: 1,
            isRequired: true,
          },
        ],
      },
    ],
    totalCourses: 3,
    totalDuration: 270,
    estimatedWeeks: 2,
    skills: [
      {
        skillId: 'skill-osha',
        skillName: 'OSHA Compliance',
        levelBefore: 0,
        levelAfter: 85,
        levelGain: 85,
      },
      {
        skillId: 'skill-safety',
        skillName: 'Workplace Safety',
        levelBefore: 0,
        levelAfter: 80,
        levelGain: 80,
      },
    ],
    certificationId: 'cert-manufacturing-safety',
    badgeId: 'badge-safety-certified',
    roleTarget: 'Manufacturing Worker',
    enrollmentCount: 15800,
    completionRate: 94,
    rating: 4.7,
    reviewCount: 3450,
    difficulty: 'beginner',
    prerequisites: [],
    isRequired: true,
    isSequential: false,
    createdAt: '2023-04-01T08:00:00Z',
    updatedAt: '2024-09-15T10:00:00Z',
    publishedAt: '2023-04-15T08:00:00Z',
    status: 'published',
  },
  {
    id: 'path-008',
    title: 'Aerospace Industry Compliance',
    slug: 'aerospace-compliance',
    description:
      'Comprehensive compliance training for aerospace industry professionals. Covers ITAR, AS9100, FAA regulations, and export control.',
    shortDescription: 'Aerospace regulatory compliance training',
    thumbnail: 'https://images.unsplash.com/photo-1517976487492-5750f3195933?w=800',
    coverImage: 'https://images.unsplash.com/photo-1517976487492-5750f3195933?w=1600',
    stages: [
      {
        id: 'path-008-stage-1',
        title: 'ITAR Fundamentals',
        description: 'Export control regulations',
        order: 1,
        items: [
          {
            id: 'item-1',
            type: 'course',
            resourceId: 'course-itar',
            title: 'ITAR Compliance Training',
            duration: 120,
            order: 1,
            isRequired: true,
          },
        ],
      },
      {
        id: 'path-008-stage-2',
        title: 'Quality Standards',
        description: 'AS9100 requirements',
        order: 2,
        items: [
          {
            id: 'item-2',
            type: 'course',
            resourceId: 'course-as9100',
            title: 'AS9100 Quality Management',
            duration: 180,
            order: 1,
            isRequired: true,
          },
        ],
      },
      {
        id: 'path-008-stage-3',
        title: 'FAA Regulations',
        description: 'Aviation safety regulations',
        order: 3,
        items: [
          {
            id: 'item-3',
            type: 'course',
            resourceId: 'course-faa',
            title: 'FAA Regulations Overview',
            duration: 150,
            order: 1,
            isRequired: true,
          },
        ],
      },
    ],
    totalCourses: 3,
    totalDuration: 450,
    estimatedWeeks: 4,
    skills: [
      {
        skillId: 'skill-itar',
        skillName: 'ITAR Compliance',
        levelBefore: 0,
        levelAfter: 85,
        levelGain: 85,
      },
      {
        skillId: 'skill-quality',
        skillName: 'Quality Management',
        levelBefore: 0,
        levelAfter: 70,
        levelGain: 70,
      },
    ],
    certificationId: 'cert-aerospace',
    badgeId: 'badge-aerospace-certified',
    roleTarget: 'Aerospace Professional',
    enrollmentCount: 4200,
    completionRate: 88,
    rating: 4.8,
    reviewCount: 890,
    difficulty: 'intermediate',
    prerequisites: [],
    isRequired: true,
    isSequential: false,
    createdAt: '2023-08-01T08:00:00Z',
    updatedAt: '2024-08-15T14:30:00Z',
    publishedAt: '2023-08-15T08:00:00Z',
    status: 'published',
  },
];

export const mockPathEnrollments: LearningPathEnrollment[] = [
  {
    id: 'path-enroll-001',
    pathId: 'path-001',
    learnerId: 'learner-001',
    status: 'in-progress',
    progress: 45,
    currentStageId: 'path-001-stage-2',
    completedItems: ['item-1'],
    startedAt: '2024-09-01T08:00:00Z',
    estimatedCompletion: '2025-01-15T08:00:00Z',
    timeSpent: 1200,
  },
  {
    id: 'path-enroll-002',
    pathId: 'path-005',
    learnerId: 'learner-002',
    status: 'completed',
    progress: 100,
    currentStageId: 'path-005-stage-3',
    completedItems: ['item-1', 'item-2', 'item-3'],
    startedAt: '2024-10-01T08:00:00Z',
    completedAt: '2024-10-08T16:30:00Z',
    timeSpent: 340,
  },
];

// Helper functions
export function getLearningPathById(id: string): LearningPath | undefined {
  return mockLearningPaths.find((path) => path.id === id);
}

export function getRequiredLearningPaths(): LearningPath[] {
  return mockLearningPaths.filter((path) => path.isRequired);
}

export function getPopularLearningPaths(limit: number = 5): LearningPath[] {
  return [...mockLearningPaths]
    .sort((a, b) => b.enrollmentCount - a.enrollmentCount)
    .slice(0, limit);
}
