/**
 * Mock user data for LXP360
 */

import type { Instructor, Learner, LearnerGroup, Manager } from '@/types/lms';

export const mockInstructors: Instructor[] = [
  {
    id: 'inst-001',
    name: 'Dr. Sarah Chen',
    email: 'sarah.chen@lxd360.com',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    title: 'Chief Learning Scientist',
    bio: 'Dr. Chen brings 15 years of experience in learning science and instructional design. She holds a Ph.D. in Cognitive Psychology from Stanford and has published extensively on adaptive learning systems.',
    expertise: [
      'Cognitive Science',
      'Instructional Design',
      'Adaptive Learning',
      'Assessment Design',
    ],
    rating: 4.9,
    courseCount: 12,
    studentCount: 15420,
    socialLinks: {
      linkedin: 'https://linkedin.com/in/sarahchen',
      twitter: 'https://twitter.com/drsarahchen',
    },
  },
  {
    id: 'inst-002',
    name: 'Marcus Johnson',
    email: 'marcus.johnson@lxd360.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    title: 'Leadership Development Expert',
    bio: 'Marcus is a certified executive coach with 20 years of experience developing leaders at Fortune 500 companies. He specializes in emotional intelligence and transformational leadership.',
    expertise: ['Leadership', 'Executive Coaching', 'Team Building', 'Change Management'],
    rating: 4.8,
    courseCount: 8,
    studentCount: 9850,
    socialLinks: {
      linkedin: 'https://linkedin.com/in/marcusjohnson',
    },
  },
  {
    id: 'inst-003',
    name: 'Dr. Emily Rodriguez',
    email: 'emily.rodriguez@lxd360.com',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    title: 'Healthcare Compliance Director',
    bio: 'Dr. Rodriguez is a healthcare compliance expert with extensive experience in HIPAA regulations and patient safety. Former Chief Compliance Officer at major healthcare systems.',
    expertise: ['HIPAA Compliance', 'Healthcare Regulations', 'Patient Safety', 'Risk Management'],
    rating: 4.9,
    courseCount: 15,
    studentCount: 28340,
    socialLinks: {
      linkedin: 'https://linkedin.com/in/emilyrodriguez',
    },
  },
  {
    id: 'inst-004',
    name: 'James Wilson',
    email: 'james.wilson@lxd360.com',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    title: 'Senior Technical Trainer',
    bio: 'James is a full-stack developer turned educator with expertise in modern web technologies. He has trained thousands of developers at companies like Google, Meta, and Amazon.',
    expertise: ['Web Development', 'Cloud Architecture', 'DevOps', 'Software Engineering'],
    rating: 4.7,
    courseCount: 10,
    studentCount: 12560,
    socialLinks: {
      linkedin: 'https://linkedin.com/in/jameswilsondev',
      twitter: 'https://twitter.com/jameswilsontech',
      website: 'https://jameswilson.dev',
    },
  },
  {
    id: 'inst-005',
    name: 'Dr. Aisha Patel',
    email: 'aisha.patel@lxd360.com',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    title: 'Safety & Compliance Expert',
    bio: 'Dr. Patel is an industrial safety expert with OSHA certifications and 18 years of experience in manufacturing and aerospace industries.',
    expertise: ['OSHA Compliance', 'Industrial Safety', 'Risk Assessment', 'Safety Training'],
    rating: 4.8,
    courseCount: 20,
    studentCount: 45680,
    socialLinks: {
      linkedin: 'https://linkedin.com/in/aishapatel',
    },
  },
];

export const mockLearners: Learner[] = [
  {
    id: 'learner-001',
    email: 'john.smith@acmecorp.com',
    firstName: 'John',
    lastName: 'Smith',
    displayName: 'John Smith',
    avatar: 'https://images.unsplash.com/photo-1599566150163-29194dcabd36?w=150',
    role: 'learner',
    status: 'active',
    title: 'Software Engineer',
    department: 'Engineering',
    location: 'San Francisco, CA',
    timezone: 'America/Los_Angeles',
    locale: 'en-US',
    organizationId: 'org-001',
    managerId: 'manager-001',
    teamIds: ['team-eng-001'],
    groupIds: ['group-001', 'group-003'],
    level: 12,
    xp: 4520,
    xpToNextLevel: 480,
    streak: 15,
    longestStreak: 32,
    totalCourses: 24,
    completedCourses: 18,
    totalTimeSpent: 4320,
    badges: ['badge-001', 'badge-003', 'badge-007'],
    skills: [
      {
        skillId: 'skill-js',
        skillName: 'JavaScript',
        category: 'Technical',
        level: 75,
        endorsements: 12,
        courses: ['course-001'],
      },
      {
        skillId: 'skill-react',
        skillName: 'React',
        category: 'Technical',
        level: 68,
        endorsements: 8,
        courses: ['course-002'],
      },
      {
        skillId: 'skill-leadership',
        skillName: 'Leadership',
        category: 'Soft Skills',
        level: 45,
        endorsements: 3,
        courses: ['course-010'],
      },
    ],
    preferences: {
      preferredLanguage: 'en',
      contentLanguages: ['en'],
      difficultyPreference: 'challenging',
      learningPace: 'standard',
      preferredContentTypes: ['video', 'interactive'],
      dailyGoalMinutes: 30,
      weeklyGoalCourses: 2,
      emailDigest: 'weekly',
      theme: 'dark',
      compactMode: false,
      showProgress: true,
      showLeaderboard: true,
      profileVisibility: 'organization',
      showActivity: true,
      showBadges: true,
    },
    accessibilitySettings: {
      fontSize: 'medium',
      lineHeight: 'normal',
      letterSpacing: 'normal',
      fontFamily: 'default',
      highContrast: false,
      reducedMotion: false,
      colorBlindMode: 'none',
      autoPlayCaptions: true,
      preferredCaptionLanguage: 'en',
      screenReaderOptimized: false,
      audioDescriptions: false,
      focusMode: false,
      hideDecorations: false,
      showReadingGuide: false,
      extendedTime: false,
      timeExtensionPercent: 0,
      breakReminders: true,
      breakIntervalMinutes: 45,
      simplifiedInterface: false,
      chunkContent: false,
      keyboardNavigation: true,
      stickyKeys: false,
      largeClickTargets: false,
    },
    notificationSettings: {
      emailNewCourse: true,
      emailAssignments: true,
      emailDeadlines: true,
      emailCompletions: true,
      emailBadges: true,
      emailDiscussions: false,
      emailMentions: true,
      emailDigest: true,
      pushEnabled: true,
      pushAssignments: true,
      pushDeadlines: true,
      pushCompletions: true,
      pushBadges: true,
      pushDiscussions: false,
      pushMentions: true,
      inAppEnabled: true,
      soundEnabled: false,
    },
    joinedAt: '2023-06-15T08:00:00Z',
    lastActiveAt: '2024-12-08T14:30:00Z',
    lastLoginAt: '2024-12-08T09:00:00Z',
    complianceStatus: 'compliant',
    requiredTrainingCount: 5,
    overdueTrainingCount: 0,
  },
  {
    id: 'learner-002',
    email: 'maria.garcia@acmecorp.com',
    firstName: 'Maria',
    lastName: 'Garcia',
    displayName: 'Maria Garcia',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
    role: 'learner',
    status: 'active',
    title: 'Product Manager',
    department: 'Product',
    location: 'Austin, TX',
    timezone: 'America/Chicago',
    locale: 'en-US',
    organizationId: 'org-001',
    managerId: 'manager-002',
    teamIds: ['team-product-001'],
    groupIds: ['group-002', 'group-004'],
    level: 8,
    xp: 2890,
    xpToNextLevel: 610,
    streak: 7,
    longestStreak: 21,
    totalCourses: 15,
    completedCourses: 10,
    totalTimeSpent: 2880,
    badges: ['badge-002', 'badge-005'],
    skills: [
      {
        skillId: 'skill-pm',
        skillName: 'Product Management',
        category: 'Business',
        level: 82,
        endorsements: 15,
        courses: ['course-005'],
      },
      {
        skillId: 'skill-analytics',
        skillName: 'Data Analytics',
        category: 'Technical',
        level: 55,
        endorsements: 5,
        courses: ['course-006'],
      },
    ],
    preferences: {
      preferredLanguage: 'en',
      contentLanguages: ['en', 'es'],
      difficultyPreference: 'moderate',
      learningPace: 'relaxed',
      preferredContentTypes: ['video', 'text'],
      dailyGoalMinutes: 20,
      weeklyGoalCourses: 1,
      emailDigest: 'daily',
      theme: 'dark',
      compactMode: false,
      showProgress: true,
      showLeaderboard: false,
      profileVisibility: 'public',
      showActivity: true,
      showBadges: true,
    },
    accessibilitySettings: {
      fontSize: 'medium',
      lineHeight: 'relaxed',
      letterSpacing: 'normal',
      fontFamily: 'default',
      highContrast: false,
      reducedMotion: false,
      colorBlindMode: 'none',
      autoPlayCaptions: true,
      preferredCaptionLanguage: 'en',
      screenReaderOptimized: false,
      audioDescriptions: false,
      focusMode: false,
      hideDecorations: false,
      showReadingGuide: false,
      extendedTime: false,
      timeExtensionPercent: 0,
      breakReminders: false,
      breakIntervalMinutes: 60,
      simplifiedInterface: false,
      chunkContent: false,
      keyboardNavigation: false,
      stickyKeys: false,
      largeClickTargets: false,
    },
    notificationSettings: {
      emailNewCourse: true,
      emailAssignments: true,
      emailDeadlines: true,
      emailCompletions: false,
      emailBadges: true,
      emailDiscussions: true,
      emailMentions: true,
      emailDigest: true,
      pushEnabled: true,
      pushAssignments: true,
      pushDeadlines: true,
      pushCompletions: false,
      pushBadges: true,
      pushDiscussions: true,
      pushMentions: true,
      inAppEnabled: true,
      soundEnabled: true,
    },
    joinedAt: '2023-09-01T08:00:00Z',
    lastActiveAt: '2024-12-07T16:45:00Z',
    lastLoginAt: '2024-12-07T08:30:00Z',
    complianceStatus: 'at-risk',
    requiredTrainingCount: 4,
    overdueTrainingCount: 1,
  },
];

export const mockManagers: Manager[] = [
  {
    id: 'manager-001',
    user: mockLearners[0],
    teamMembers: ['learner-003', 'learner-004', 'learner-005'],
    teamMemberCount: 8,
    directReports: [],
    teamCompletionRate: 78,
    teamComplianceRate: 92,
    teamAverageScore: 84,
    teamTotalHours: 1250,
    canAssignCourses: true,
    canViewReports: true,
    canApproveEnrollments: true,
    canViewTranscripts: true,
  },
];

export const mockGroups: LearnerGroup[] = [
  {
    id: 'group-001',
    name: 'Engineering Team',
    description: 'All engineers across the organization',
    type: 'department',
    members: ['learner-001', 'learner-003', 'learner-005'],
    memberCount: 45,
    managers: ['manager-001'],
    courseAssignments: ['course-001', 'course-002', 'course-007'],
    pathAssignments: ['path-001'],
    createdAt: '2023-01-15T08:00:00Z',
    updatedAt: '2024-11-01T10:30:00Z',
  },
  {
    id: 'group-002',
    name: 'Product Team',
    description: 'Product managers and designers',
    type: 'department',
    members: ['learner-002', 'learner-004'],
    memberCount: 18,
    managers: ['manager-002'],
    courseAssignments: ['course-005', 'course-006'],
    pathAssignments: ['path-002'],
    createdAt: '2023-01-15T08:00:00Z',
    updatedAt: '2024-10-15T14:20:00Z',
  },
  {
    id: 'group-003',
    name: 'New Hire Cohort Q4 2024',
    description: 'Q4 2024 onboarding cohort',
    type: 'cohort',
    members: ['learner-010', 'learner-011', 'learner-012'],
    memberCount: 15,
    managers: ['manager-001', 'manager-002'],
    courseAssignments: ['course-onboarding', 'course-security'],
    pathAssignments: ['path-onboarding'],
    createdAt: '2024-10-01T08:00:00Z',
    updatedAt: '2024-12-01T09:00:00Z',
  },
  {
    id: 'group-004',
    name: 'Leadership Development Program',
    description: 'High-potential employees in leadership track',
    type: 'cohort',
    members: ['learner-002', 'learner-006', 'learner-008'],
    memberCount: 12,
    managers: ['manager-002'],
    courseAssignments: ['course-010', 'course-011', 'course-012'],
    pathAssignments: ['path-leadership'],
    createdAt: '2024-06-01T08:00:00Z',
    updatedAt: '2024-11-20T11:45:00Z',
  },
];

// Generate more learners for realistic data
export function generateMockLearners(count: number): Learner[] {
  const firstNames = [
    'Alex',
    'Jordan',
    'Taylor',
    'Morgan',
    'Casey',
    'Riley',
    'Quinn',
    'Avery',
    'Cameron',
    'Drew',
    'Sam',
    'Charlie',
    'Jamie',
    'Dana',
    'Robin',
  ];
  const lastNames = [
    'Williams',
    'Brown',
    'Davis',
    'Miller',
    'Wilson',
    'Moore',
    'Taylor',
    'Anderson',
    'Thomas',
    'Jackson',
    'White',
    'Harris',
    'Martin',
    'Thompson',
    'Lee',
  ];
  const departments = [
    'Engineering',
    'Product',
    'Marketing',
    'Sales',
    'HR',
    'Finance',
    'Operations',
    'Customer Success',
  ];
  const locations = [
    'San Francisco, CA',
    'New York, NY',
    'Austin, TX',
    'Seattle, WA',
    'Boston, MA',
    'Denver, CO',
    'Chicago, IL',
    'Remote',
  ];

  return Array.from({ length: count }, (_, i) => {
    const firstName = firstNames[Math.floor(Math.random() * firstNames.length)];
    const lastName = lastNames[Math.floor(Math.random() * lastNames.length)];
    const level = Math.floor(Math.random() * 20) + 1;

    return {
      id: `learner-gen-${i + 1}`,
      email: `${firstName.toLowerCase()}.${lastName.toLowerCase()}${i}@acmecorp.com`,
      firstName,
      lastName,
      displayName: `${firstName} ${lastName}`,
      avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=${firstName}${lastName}${i}`,
      role: 'learner' as const,
      status: 'active' as const,
      title: ['Engineer', 'Manager', 'Analyst', 'Specialist', 'Director'][
        Math.floor(Math.random() * 5)
      ],
      department: departments[Math.floor(Math.random() * departments.length)],
      location: locations[Math.floor(Math.random() * locations.length)],
      timezone: 'America/Los_Angeles',
      locale: 'en-US',
      organizationId: 'org-001',
      teamIds: [`team-${Math.floor(Math.random() * 5) + 1}`],
      groupIds: [`group-00${Math.floor(Math.random() * 4) + 1}`],
      level,
      xp: level * 500 + Math.floor(Math.random() * 500),
      xpToNextLevel: 500 - Math.floor(Math.random() * 500),
      streak: Math.floor(Math.random() * 30),
      longestStreak: Math.floor(Math.random() * 60) + 10,
      totalCourses: Math.floor(Math.random() * 30) + 5,
      completedCourses: Math.floor(Math.random() * 20) + 3,
      totalTimeSpent: Math.floor(Math.random() * 5000) + 500,
      badges: [`badge-00${Math.floor(Math.random() * 9) + 1}`],
      skills: [],
      preferences: {
        preferredLanguage: 'en',
        contentLanguages: ['en'],
        difficultyPreference: 'moderate' as const,
        learningPace: 'standard' as const,
        preferredContentTypes: ['video'],
        dailyGoalMinutes: 30,
        weeklyGoalCourses: 2,
        emailDigest: 'weekly' as const,
        theme: 'dark' as const,
        compactMode: false,
        showProgress: true,
        showLeaderboard: true,
        profileVisibility: 'organization' as const,
        showActivity: true,
        showBadges: true,
      },
      accessibilitySettings: {
        fontSize: 'medium' as const,
        lineHeight: 'normal' as const,
        letterSpacing: 'normal' as const,
        fontFamily: 'default' as const,
        highContrast: false,
        reducedMotion: false,
        colorBlindMode: 'none' as const,
        autoPlayCaptions: true,
        preferredCaptionLanguage: 'en',
        screenReaderOptimized: false,
        audioDescriptions: false,
        focusMode: false,
        hideDecorations: false,
        showReadingGuide: false,
        extendedTime: false,
        timeExtensionPercent: 0,
        breakReminders: true,
        breakIntervalMinutes: 45,
        simplifiedInterface: false,
        chunkContent: false,
        keyboardNavigation: true,
        stickyKeys: false,
        largeClickTargets: false,
      },
      notificationSettings: {
        emailNewCourse: true,
        emailAssignments: true,
        emailDeadlines: true,
        emailCompletions: true,
        emailBadges: true,
        emailDiscussions: false,
        emailMentions: true,
        emailDigest: true,
        pushEnabled: true,
        pushAssignments: true,
        pushDeadlines: true,
        pushCompletions: true,
        pushBadges: true,
        pushDiscussions: false,
        pushMentions: true,
        inAppEnabled: true,
        soundEnabled: false,
      },
      joinedAt: new Date(Date.now() - Math.random() * 365 * 24 * 60 * 60 * 1000).toISOString(),
      lastActiveAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
      lastLoginAt: new Date(Date.now() - Math.random() * 3 * 24 * 60 * 60 * 1000).toISOString(),
      complianceStatus: (['compliant', 'at-risk', 'compliant', 'compliant'] as const)[
        Math.floor(Math.random() * 4)
      ],
      requiredTrainingCount: Math.floor(Math.random() * 5) + 2,
      overdueTrainingCount: Math.floor(Math.random() * 2),
    };
  });
}
