/**
 * Pricing Data
 * Static pricing data for all products, tiers, and add-ons
 * In production, this would be fetched from content service
 */

import type { PricingAddon, PricingDiscount, PricingProduct, PricingTier } from '@/types/pricing';

// ============================================================================
// INSPIRE STUDIO TIERS
// ============================================================================

const inspireStudioTiers: PricingTier[] = [
  {
    id: 'inspire-creator',
    name: 'Creator',
    slug: 'creator',
    productId: 'inspire-studio',
    tierLevel: 'starter',
    targetAudience: 'For solo course creators',
    priceMonthly: 8900,
    priceYearly: 106900,
    isCustomPricing: false,
    authorSeats: 1,
    storageGB: 10,
    monthlyTokens: 50000,
    features: [],
    highlightFeatures: [
      'AI content generation',
      'SCORM/xAPI export',
      '10 GB storage',
      '50K AI tokens/month',
      'Email support',
    ],
    includedAddons: [],
    isPopular: false,
    ctaText: 'Start Free Trial',
    displayOrder: 1,
    isActive: true,
    trialDays: 14,
  },
  {
    id: 'inspire-team',
    name: 'Team',
    slug: 'team',
    productId: 'inspire-studio',
    tierLevel: 'growth',
    targetAudience: 'For growing L&D teams',
    priceMonthly: 32100,
    priceQuarterly: 91300,
    priceYearly: 385200,
    isCustomPricing: false,
    authorSeats: 3,
    storageGB: 50,
    monthlyTokens: 250000,
    features: [],
    highlightFeatures: [
      'Everything in Creator',
      '3 author seats',
      'Team collaboration',
      '50 GB storage',
      '250K AI tokens/month',
      'Priority support',
    ],
    includedAddons: [],
    isPopular: true,
    popularBadgeText: 'Most Popular',
    ctaText: 'Start Free Trial',
    displayOrder: 2,
    isActive: true,
    trialDays: 14,
  },
  {
    id: 'inspire-business',
    name: 'Business',
    slug: 'business',
    productId: 'inspire-studio',
    tierLevel: 'professional',
    targetAudience: 'For established L&D departments',
    priceMonthly: 89000,
    priceQuarterly: 253000,
    priceYearly: 1068000,
    isCustomPricing: false,
    authorSeats: 10,
    storageGB: 200,
    monthlyTokens: 1000000,
    features: [],
    highlightFeatures: [
      'Everything in Team',
      '10 author seats',
      'Advanced collaboration',
      '200 GB storage',
      '1M AI tokens/month',
      'SSO/SAML',
      'Priority support',
    ],
    includedAddons: [],
    isPopular: false,
    ctaText: 'Start Free Trial',
    displayOrder: 3,
    isActive: true,
    trialDays: 14,
  },
  {
    id: 'inspire-enterprise',
    name: 'Enterprise',
    slug: 'enterprise',
    productId: 'inspire-studio',
    tierLevel: 'enterprise',
    targetAudience: 'For large organizations',
    isCustomPricing: true,
    features: [],
    highlightFeatures: [
      'Unlimited author seats',
      'Unlimited storage',
      'Custom AI token allocation',
      'SSO/SAML',
      'Custom integrations',
      'Dedicated support',
      'SLA guarantee',
    ],
    includedAddons: [],
    isPopular: false,
    ctaText: 'Contact Sales',
    displayOrder: 4,
    isActive: true,
  },
];

// ============================================================================
// LXP360 TIERS
// ============================================================================

const lxp360Tiers: PricingTier[] = [
  {
    id: 'lxp-micro',
    name: 'Micro',
    slug: 'micro',
    productId: 'lxp360',
    tierLevel: 'micro',
    targetAudience: 'For small teams',
    priceMonthly: 3900,
    priceYearly: 47000,
    isCustomPricing: false,
    learnerLimit: 5,
    storageGB: 10,
    features: [],
    highlightFeatures: [
      'Full LMS features',
      'Basic analytics',
      '10 GB storage',
      'SCORM/xAPI support',
      'Email support',
    ],
    includedAddons: [],
    isPopular: false,
    ctaText: 'Start Free Trial',
    displayOrder: 1,
    isActive: true,
    trialDays: 14,
  },
  {
    id: 'lxp-growth',
    name: 'Growth',
    slug: 'growth',
    productId: 'lxp360',
    tierLevel: 'growth',
    targetAudience: 'For growing companies',
    priceMonthly: 15900,
    priceQuarterly: 45200,
    priceYearly: 191000,
    isCustomPricing: false,
    learnerLimit: 20,
    storageGB: 50,
    features: [],
    highlightFeatures: [
      'Everything in Micro',
      'Learning paths',
      'Gamification',
      '50 GB storage',
      'Advanced reporting',
      'Priority support',
    ],
    includedAddons: [],
    isPopular: false,
    ctaText: 'Start Free Trial',
    displayOrder: 2,
    isActive: true,
    trialDays: 14,
  },
  {
    id: 'lxp-scale',
    name: 'Scale',
    slug: 'scale',
    productId: 'lxp360',
    tierLevel: 'scale',
    targetAudience: 'For mid-size organizations',
    priceMonthly: 40000,
    priceQuarterly: 113600,
    priceYearly: 480000,
    isCustomPricing: false,
    learnerLimit: 100,
    storageGB: 200,
    features: [],
    highlightFeatures: [
      'Everything in Growth',
      'Adaptive learning (AI)',
      'Full LRS access',
      '200 GB storage',
      'API access',
      'SSO/SAML',
    ],
    includedAddons: [],
    isPopular: true,
    popularBadgeText: 'Most Popular',
    ctaText: 'Start Free Trial',
    displayOrder: 3,
    isActive: true,
    trialDays: 14,
  },
  {
    id: 'lxp-professional',
    name: 'Professional',
    slug: 'professional',
    productId: 'lxp360',
    tierLevel: 'professional',
    targetAudience: 'For large teams',
    priceMonthly: 150000,
    priceQuarterly: 426000,
    priceYearly: 1800000,
    isCustomPricing: false,
    learnerLimit: 500,
    storageGB: 500,
    features: [],
    highlightFeatures: [
      'Everything in Scale',
      '500 learners',
      'Advanced AI features',
      '500 GB storage',
      'Custom branding',
      'Dedicated support',
    ],
    includedAddons: [],
    isPopular: false,
    ctaText: 'Start Free Trial',
    displayOrder: 4,
    isActive: true,
    trialDays: 14,
  },
  {
    id: 'lxp-enterprise',
    name: 'Enterprise',
    slug: 'enterprise',
    productId: 'lxp360',
    tierLevel: 'enterprise',
    targetAudience: 'For large enterprises',
    isCustomPricing: true,
    learnerLimit: -1, // Unlimited
    features: [],
    highlightFeatures: [
      'Unlimited learners',
      'Multi-tenant support',
      'Custom integrations',
      'BigQuery analytics',
      'Dedicated instance',
      'Platinum support',
      '99.9% SLA',
    ],
    includedAddons: [],
    isPopular: false,
    ctaText: 'Contact Sales',
    displayOrder: 5,
    isActive: true,
  },
];

// ============================================================================
// LXD360 COMPLETE (BUNDLE) TIERS
// ============================================================================

const lxd360Tiers: PricingTier[] = [
  {
    id: 'lxd-solopreneur',
    name: 'Solopreneur',
    slug: 'solopreneur',
    productId: 'lxd360',
    tierLevel: 'starter',
    targetAudience: 'For independent consultants',
    priceMonthly: 11700,
    priceYearly: 140000,
    isCustomPricing: false,
    authorSeats: 1,
    learnerLimit: 5,
    storageGB: 20,
    features: [],
    highlightFeatures: [
      '1 INSPIRE Studio seat',
      'LXP360 Micro (5 learners)',
      'Unified dashboard',
      'Seamless publishing',
      'Combined support',
    ],
    includedAddons: [],
    isPopular: false,
    ctaText: 'Start Free Trial',
    displayOrder: 1,
    isActive: true,
    trialDays: 14,
  },
  {
    id: 'lxd-agency',
    name: 'Agency',
    slug: 'agency',
    productId: 'lxd360',
    tierLevel: 'growth',
    targetAudience: 'For training companies',
    priceMonthly: 37500,
    priceYearly: 450000,
    isCustomPricing: false,
    authorSeats: 3,
    learnerLimit: 20,
    storageGB: 100,
    features: [],
    highlightFeatures: [
      '3 INSPIRE Studio seats',
      'LXP360 Growth (20 learners)',
      'Multi-client workspace',
      'White label included',
      'Client billing tools',
    ],
    includedAddons: [],
    isPopular: true,
    popularBadgeText: 'Best Value',
    ctaText: 'Start Free Trial',
    displayOrder: 2,
    isActive: true,
    trialDays: 14,
  },
  {
    id: 'lxd-corporate',
    name: 'Corporate',
    slug: 'corporate',
    productId: 'lxd360',
    tierLevel: 'professional',
    targetAudience: 'For internal L&D teams',
    priceMonthly: 63800,
    priceYearly: 765000,
    isCustomPricing: false,
    authorSeats: 3,
    learnerLimit: 100,
    storageGB: 300,
    features: [],
    highlightFeatures: [
      '3 INSPIRE Studio seats',
      'LXP360 Scale (100 learners)',
      'Adaptive learning',
      'Full analytics',
      'HRIS integration',
    ],
    includedAddons: [],
    isPopular: false,
    ctaText: 'Start Free Trial',
    displayOrder: 3,
    isActive: true,
    trialDays: 14,
  },
  {
    id: 'lxd-enterprise',
    name: 'Enterprise',
    slug: 'enterprise',
    productId: 'lxd360',
    tierLevel: 'enterprise',
    targetAudience: 'For large organizations',
    isCustomPricing: true,
    authorSeats: -1, // Unlimited
    learnerLimit: -1, // Unlimited
    features: [],
    highlightFeatures: [
      'Unlimited everything',
      'Dedicated infrastructure',
      'Custom development',
      'Strategic consulting',
      'Quarterly reviews',
      '99.9% SLA',
    ],
    includedAddons: [],
    isPopular: false,
    ctaText: 'Contact Sales',
    displayOrder: 4,
    isActive: true,
  },
];

// ============================================================================
// PRODUCTS
// ============================================================================

export const products: PricingProduct[] = [
  {
    id: 'inspire-studio',
    name: 'INSPIRE Studio',
    slug: 'inspire-studio',
    productType: 'inspire_studio',
    tagline: 'AI-Powered Course Authoring',
    description:
      'Create stunning eLearning content with AI assistance, built-in project management, and the INSPIRE framework.',
    icon: 'Sparkles',
    color: '#BA23FB',
    features: [],
    tiers: inspireStudioTiers,
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'lxp360',
    name: 'LXP360',
    slug: 'lxp360',
    productType: 'lxp360',
    tagline: 'Learning Experience Platform',
    description:
      'Enterprise LMS + LXP + LRS with AI-powered adaptive learning, compliance tracking, and advanced analytics.',
    icon: 'GraduationCap',
    color: '#479DFF',
    features: [],
    tiers: lxp360Tiers,
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'lxd360',
    name: 'LXD360 Complete',
    slug: 'lxd360',
    productType: 'lxd360_complete',
    tagline: 'The Full Learning Stack',
    description:
      'Author + Deliver + Analyze in one unified platform. The complete learning ecosystem for modern organizations.',
    icon: 'Layers',
    color: '#10b981',
    features: [],
    tiers: lxd360Tiers,
    displayOrder: 3,
    isActive: true,
  },
];

// ============================================================================
// ADD-ONS
// ============================================================================

export const addons: PricingAddon[] = [
  // AI Add-ons
  {
    id: 'addon-ai-power-pack',
    name: 'AI Power Pack',
    slug: 'ai-power-pack',
    description: '50K extra AI tokens per month for content generation',
    category: 'ai',
    icon: 'Zap',
    priceMonthly: 5000,
    priceYearly: 48000,
    applicableProductIds: ['inspire-studio', 'lxd360'],
    minimumTier: 'all',
    includedInTierIds: [],
    requiredAddonIds: [],
    incompatibleAddonIds: [],
    features: [
      '50,000 additional AI tokens/month',
      'Priority AI processing',
      'Advanced AI models access',
    ],
    displayOrder: 1,
    isActive: true,
    isPopular: true,
  },
  {
    id: 'addon-adaptive-ai-pro',
    name: 'Adaptive AI Pro',
    slug: 'adaptive-ai-pro',
    description: 'Advanced adaptive learning with real-time personalization',
    category: 'ai',
    icon: 'Brain',
    priceMonthly: 19900,
    priceYearly: 191000,
    applicableProductIds: ['lxp360', 'lxd360'],
    minimumTier: 'growth',
    includedInTierIds: [],
    requiredAddonIds: [],
    incompatibleAddonIds: ['addon-adaptive-ai-enterprise'],
    features: [
      'Real-time learning path optimization',
      'Predictive analytics',
      'Knowledge gap analysis',
      'Personalized recommendations',
    ],
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'addon-adaptive-ai-enterprise',
    name: 'Adaptive AI Enterprise',
    slug: 'adaptive-ai-enterprise',
    description: 'Enterprise-grade adaptive learning with custom models',
    category: 'ai',
    icon: 'Cpu',
    priceMonthly: 49900,
    priceYearly: 479000,
    applicableProductIds: ['lxp360', 'lxd360'],
    minimumTier: 'professional',
    includedInTierIds: [],
    requiredAddonIds: [],
    incompatibleAddonIds: ['addon-adaptive-ai-pro'],
    features: [
      'Everything in Adaptive AI Pro',
      'Custom AI model training',
      'Dedicated AI infrastructure',
      'Advanced predictive modeling',
      'API access to AI features',
    ],
    displayOrder: 3,
    isActive: true,
  },

  // Engagement Add-ons
  {
    id: 'addon-social-learning',
    name: 'Social Learning',
    slug: 'social-learning',
    description: 'Discussion forums, peer learning, and social features',
    category: 'engagement',
    icon: 'Users',
    priceMonthly: 9900,
    priceYearly: 95000,
    applicableProductIds: ['lxp360', 'lxd360'],
    minimumTier: 'growth',
    includedInTierIds: [],
    requiredAddonIds: [],
    incompatibleAddonIds: [],
    features: [
      'Discussion forums',
      'Peer-to-peer messaging',
      'Expert Q&A',
      'Social profiles',
      'Activity feeds',
    ],
    displayOrder: 4,
    isActive: true,
    isPopular: true,
  },
  {
    id: 'addon-advanced-gamification',
    name: 'Advanced Gamification',
    slug: 'advanced-gamification',
    description: 'Badges, leaderboards, achievements, and rewards',
    category: 'engagement',
    icon: 'Trophy',
    priceMonthly: 7900,
    priceYearly: 75800,
    applicableProductIds: ['lxp360', 'lxd360'],
    minimumTier: 'growth',
    includedInTierIds: [],
    requiredAddonIds: [],
    incompatibleAddonIds: [],
    features: [
      'Custom badges & achievements',
      'Multiple leaderboards',
      'Points & rewards system',
      'Challenges & competitions',
      'Progress streaks',
    ],
    displayOrder: 5,
    isActive: true,
  },

  // Branding Add-ons
  {
    id: 'addon-white-label-basic',
    name: 'White Label Basic',
    slug: 'white-label-basic',
    description: 'Remove LXD360 branding and add your logo',
    category: 'branding',
    icon: 'Palette',
    priceMonthly: 4900,
    priceYearly: 47000,
    applicableProductIds: ['lxp360', 'lxd360'],
    minimumTier: 'growth',
    includedInTierIds: [],
    requiredAddonIds: [],
    incompatibleAddonIds: ['addon-white-label-pro', 'addon-white-label-agency'],
    features: [
      'Remove LXD360 branding',
      'Custom logo',
      'Primary color customization',
      'Custom favicon',
    ],
    displayOrder: 6,
    isActive: true,
  },
  {
    id: 'addon-white-label-pro',
    name: 'White Label Pro',
    slug: 'white-label-pro',
    description: 'Full brand customization with custom themes',
    category: 'branding',
    icon: 'Brush',
    priceMonthly: 14900,
    priceYearly: 143000,
    applicableProductIds: ['lxp360', 'lxd360'],
    minimumTier: 'scale',
    includedInTierIds: [],
    requiredAddonIds: [],
    incompatibleAddonIds: ['addon-white-label-basic', 'addon-white-label-agency'],
    features: [
      'Everything in White Label Basic',
      'Custom CSS/themes',
      'Custom login page',
      'Custom email templates',
      'Custom certificates',
    ],
    displayOrder: 7,
    isActive: true,
    isPopular: true,
  },
  {
    id: 'addon-white-label-agency',
    name: 'White Label Agency',
    slug: 'white-label-agency',
    description: 'Multi-brand support for agencies and resellers',
    category: 'branding',
    icon: 'Building2',
    priceMonthly: 49900,
    priceYearly: 479000,
    applicableProductIds: ['lxp360', 'lxd360'],
    minimumTier: 'professional',
    includedInTierIds: [],
    requiredAddonIds: [],
    incompatibleAddonIds: ['addon-white-label-basic', 'addon-white-label-pro'],
    features: [
      'Everything in White Label Pro',
      'Unlimited client brands',
      'Per-client theming',
      'Client management portal',
      'Reseller billing support',
    ],
    displayOrder: 8,
    isActive: true,
  },
  {
    id: 'addon-custom-domain',
    name: 'Custom Domain',
    slug: 'custom-domain',
    description: 'Use your own domain (learning.yourcompany.com)',
    category: 'branding',
    icon: 'Globe',
    priceMonthly: 2900,
    priceYearly: 27800,
    applicableProductIds: ['lxp360', 'lxd360'],
    minimumTier: 'all',
    includedInTierIds: [],
    requiredAddonIds: [],
    incompatibleAddonIds: [],
    features: [
      'Custom domain setup',
      'SSL certificate included',
      'DNS management',
      'Email configuration',
    ],
    displayOrder: 9,
    isActive: true,
  },
  {
    id: 'addon-branded-mobile-app',
    name: 'Branded Mobile App',
    slug: 'branded-mobile-app',
    description: 'Your own branded iOS and Android app',
    category: 'branding',
    icon: 'Smartphone',
    priceMonthly: 19900,
    priceYearly: 191000,
    applicableProductIds: ['lxp360', 'lxd360'],
    minimumTier: 'scale',
    includedInTierIds: [],
    requiredAddonIds: [],
    incompatibleAddonIds: [],
    features: [
      'Custom branded iOS app',
      'Custom branded Android app',
      'Push notifications',
      'Offline learning',
      'App store submission support',
    ],
    displayOrder: 10,
    isActive: true,
  },

  // Integration Add-ons
  {
    id: 'addon-multi-lms-distribution',
    name: 'Multi-LMS Distribution',
    slug: 'multi-lms-distribution',
    description: 'Distribute content to multiple LMS platforms',
    category: 'integration',
    icon: 'Share2',
    priceMonthly: 9900,
    priceYearly: 95000,
    applicableProductIds: ['inspire-studio', 'lxd360'],
    minimumTier: 'growth',
    includedInTierIds: [],
    requiredAddonIds: [],
    incompatibleAddonIds: [],
    features: [
      'One-click multi-LMS publish',
      'Support for major LMS platforms',
      'Version management',
      'Analytics aggregation',
    ],
    displayOrder: 11,
    isActive: true,
  },
  {
    id: 'addon-lrs-connector',
    name: 'LRS Connector',
    slug: 'lrs-connector',
    description: 'Connect to external Learning Record Stores',
    category: 'integration',
    icon: 'Database',
    priceMonthly: 4900,
    priceYearly: 47000,
    applicableProductIds: ['lxp360', 'lxd360'],
    minimumTier: 'growth',
    includedInTierIds: [],
    requiredAddonIds: [],
    incompatibleAddonIds: [],
    features: [
      'xAPI statement forwarding',
      'Support for major LRS providers',
      'Custom statement mapping',
      'Real-time sync',
    ],
    displayOrder: 12,
    isActive: true,
  },
  {
    id: 'addon-hris-integration',
    name: 'HRIS Integration',
    slug: 'hris-integration',
    description: 'Sync users with your HR systems',
    category: 'integration',
    icon: 'Users',
    priceMonthly: 14900,
    priceYearly: 143000,
    applicableProductIds: ['lxp360', 'lxd360'],
    minimumTier: 'scale',
    includedInTierIds: [],
    requiredAddonIds: [],
    incompatibleAddonIds: [],
    features: [
      'Workday integration',
      'ADP integration',
      'BambooHR integration',
      'Custom HRIS via API',
      'Automated user provisioning',
    ],
    displayOrder: 13,
    isActive: true,
    isPopular: true,
  },

  // Security Add-ons
  {
    id: 'addon-sso-saml',
    name: 'SSO/SAML',
    slug: 'sso-saml',
    description: 'Single sign-on with SAML 2.0 support',
    category: 'security',
    icon: 'Key',
    priceMonthly: 9900,
    priceYearly: 95000,
    applicableProductIds: ['lxp360', 'lxd360'],
    minimumTier: 'scale',
    includedInTierIds: [],
    requiredAddonIds: [],
    incompatibleAddonIds: [],
    features: [
      'SAML 2.0 support',
      'Azure AD, Okta, OneLogin',
      'JIT user provisioning',
      'Group mapping',
    ],
    displayOrder: 14,
    isActive: true,
  },

  // Compliance Add-ons
  {
    id: 'addon-accessibility-pro',
    name: 'Accessibility Pro',
    slug: 'accessibility-pro',
    description: 'WCAG 2.1 AA compliance tools and reporting',
    category: 'compliance',
    icon: 'Accessibility',
    priceMonthly: 9900,
    priceYearly: 95000,
    applicableProductIds: ['inspire-studio', 'lxp360', 'lxd360'],
    minimumTier: 'growth',
    includedInTierIds: [],
    requiredAddonIds: [],
    incompatibleAddonIds: ['addon-accessibility-enterprise'],
    features: [
      'WCAG 2.1 AA checker',
      'Automated accessibility testing',
      'Remediation suggestions',
      'Compliance reports',
    ],
    displayOrder: 15,
    isActive: true,
  },
  {
    id: 'addon-accessibility-enterprise',
    name: 'Accessibility Enterprise',
    slug: 'accessibility-enterprise',
    description: 'Full VPAT support and accessibility consulting',
    category: 'compliance',
    icon: 'ShieldCheck',
    priceMonthly: 29900,
    priceYearly: 287000,
    applicableProductIds: ['inspire-studio', 'lxp360', 'lxd360'],
    minimumTier: 'professional',
    includedInTierIds: [],
    requiredAddonIds: [],
    incompatibleAddonIds: ['addon-accessibility-pro'],
    features: [
      'Everything in Accessibility Pro',
      'VPAT documentation',
      'Section 508 compliance',
      'Quarterly audits',
      'Remediation support',
    ],
    displayOrder: 16,
    isActive: true,
  },
  {
    id: 'addon-neurodiversity-toolkit',
    name: 'Neurodiversity Toolkit',
    slug: 'neurodiversity-toolkit',
    description: 'Tools for neurodiverse learners',
    category: 'compliance',
    icon: 'Brain',
    priceMonthly: 7900,
    priceYearly: 75800,
    applicableProductIds: ['lxp360', 'lxd360'],
    minimumTier: 'growth',
    includedInTierIds: [],
    requiredAddonIds: [],
    incompatibleAddonIds: [],
    features: [
      'Dyslexia-friendly fonts',
      'Focus mode',
      'Reading assistance',
      'Custom navigation options',
      'Sensory considerations',
    ],
    displayOrder: 17,
    isActive: true,
    isNew: true,
  },
  {
    id: 'addon-compliance-automation',
    name: 'Compliance Automation',
    slug: 'compliance-automation',
    description: 'Automate compliance training and certifications',
    category: 'compliance',
    icon: 'ClipboardCheck',
    priceMonthly: 19900,
    priceYearly: 191000,
    applicableProductIds: ['lxp360', 'lxd360'],
    minimumTier: 'scale',
    includedInTierIds: [],
    requiredAddonIds: [],
    incompatibleAddonIds: [],
    features: [
      'Automated enrollment',
      'Certification tracking',
      'Expiration reminders',
      'Audit trails',
      'Regulatory reporting',
    ],
    displayOrder: 18,
    isActive: true,
  },

  // Analytics Add-ons
  {
    id: 'addon-cognitive-insights',
    name: 'Cognitive Insights',
    slug: 'cognitive-insights',
    description: 'Deep learning analytics and cognitive load monitoring',
    category: 'analytics',
    icon: 'Activity',
    priceMonthly: 14900,
    priceYearly: 143000,
    applicableProductIds: ['lxp360', 'lxd360'],
    minimumTier: 'scale',
    includedInTierIds: [],
    requiredAddonIds: [],
    incompatibleAddonIds: [],
    features: [
      'Cognitive load analysis',
      'Attention tracking',
      'Learning efficiency metrics',
      'Fatigue detection',
    ],
    displayOrder: 19,
    isActive: true,
    isNew: true,
  },
  {
    id: 'addon-advanced-analytics',
    name: 'Advanced Analytics',
    slug: 'advanced-analytics',
    description: 'Custom dashboards, exports, and BI integration',
    category: 'analytics',
    icon: 'BarChart3',
    priceMonthly: 19900,
    priceYearly: 191000,
    applicableProductIds: ['lxp360', 'lxd360'],
    minimumTier: 'scale',
    includedInTierIds: [],
    requiredAddonIds: [],
    incompatibleAddonIds: [],
    features: [
      'Custom dashboards',
      'Scheduled reports',
      'Data export (CSV, Excel)',
      'BI tool integration',
      'BigQuery access',
    ],
    displayOrder: 20,
    isActive: true,
  },

  // Infrastructure Add-ons
  {
    id: 'addon-storage-expansion',
    name: 'Storage Expansion',
    slug: 'storage-expansion',
    description: 'Additional 500GB of storage',
    category: 'infrastructure',
    icon: 'HardDrive',
    priceMonthly: 2000,
    priceYearly: 19200,
    applicableProductIds: ['inspire-studio', 'lxp360', 'lxd360'],
    minimumTier: 'all',
    includedInTierIds: [],
    requiredAddonIds: [],
    incompatibleAddonIds: [],
    features: ['500GB additional storage', 'CDN delivery', 'No file size limits'],
    limits: {
      storage: 500,
    },
    displayOrder: 21,
    isActive: true,
  },

  // Support Add-ons
  {
    id: 'addon-premium-support',
    name: 'Premium Support',
    slug: 'premium-support',
    description: '4-hour SLA with dedicated support team',
    category: 'support',
    icon: 'HeadphonesIcon',
    priceMonthly: 29900,
    priceYearly: 287000,
    applicableProductIds: ['inspire-studio', 'lxp360', 'lxd360'],
    minimumTier: 'scale',
    includedInTierIds: [],
    requiredAddonIds: [],
    incompatibleAddonIds: ['addon-platinum-support'],
    features: [
      '4-hour response SLA',
      'Phone support',
      'Screen sharing sessions',
      'Dedicated support queue',
    ],
    displayOrder: 22,
    isActive: true,
  },
  {
    id: 'addon-platinum-support',
    name: 'Platinum Support',
    slug: 'platinum-support',
    description: '1-hour SLA with named support engineer',
    category: 'support',
    icon: 'Crown',
    priceMonthly: 99900,
    priceYearly: 959000,
    applicableProductIds: ['inspire-studio', 'lxp360', 'lxd360'],
    minimumTier: 'professional',
    includedInTierIds: [],
    requiredAddonIds: [],
    incompatibleAddonIds: ['addon-premium-support'],
    features: [
      '1-hour response SLA',
      'Named support engineer',
      '24/7 availability',
      'Proactive monitoring',
      'Monthly health checks',
    ],
    displayOrder: 23,
    isActive: true,
  },

  // Revenue Add-ons
  {
    id: 'addon-ecommerce-pro',
    name: 'E-Commerce Pro',
    slug: 'ecommerce-pro',
    description: 'Sell courses with built-in commerce features',
    category: 'revenue',
    icon: 'ShoppingCart',
    priceMonthly: 9900,
    priceYearly: 95000,
    applicableProductIds: ['lxp360', 'lxd360'],
    minimumTier: 'growth',
    includedInTierIds: [],
    requiredAddonIds: [],
    incompatibleAddonIds: [],
    features: [
      'Course marketplace',
      'Stripe/PayPal integration',
      'Coupons & promotions',
      'Subscription management',
      'Revenue reporting',
    ],
    displayOrder: 24,
    isActive: true,
    isPopular: true,
  },
];

// ============================================================================
// DISCOUNTS
// ============================================================================

export const discounts: PricingDiscount[] = [
  {
    id: 'discount-education',
    name: 'Education Discount',
    slug: 'education',
    description: '25% off for educational institutions',
    discountType: 'education',
    icon: 'GraduationCap',
    discountPercent: 25,
    applicableProductIds: [],
    applicableTierIds: [],
    excludedAddonIds: [],
    minimumCommitment: 'none',
    isStackable: false,
    usesPerCustomer: 1,
    eligibility: [
      'Valid .edu email address',
      'Accredited educational institution',
      'Students, faculty, or staff',
    ],
    verificationMethod: 'email',
    allowedDomains: ['.edu', '.edu.au', '.ac.uk', '.edu.cn'],
    displayOrder: 1,
    isActive: true,
    showOnPricingPage: true,
    ctaText: 'Verify Education Status',
    ctaUrl: '/pricing/education',
  },
  {
    id: 'discount-nonprofit',
    name: 'Nonprofit Discount',
    slug: 'nonprofit',
    description: '20% off for registered nonprofits',
    discountType: 'nonprofit',
    icon: 'Heart',
    discountPercent: 20,
    applicableProductIds: [],
    applicableTierIds: [],
    excludedAddonIds: [],
    minimumCommitment: 'none',
    isStackable: false,
    usesPerCustomer: 1,
    eligibility: [
      '501(c)(3) status in the US',
      'Registered charity (international)',
      'Valid tax-exempt documentation',
    ],
    verificationMethod: 'document',
    requiredDocuments: ['IRS determination letter', 'Tax-exempt certificate'],
    displayOrder: 2,
    isActive: true,
    showOnPricingPage: true,
    ctaText: 'Apply for Nonprofit Pricing',
    ctaUrl: '/contact?subject=nonprofit',
  },
  {
    id: 'discount-startup',
    name: 'Startup Discount',
    slug: 'startup',
    description: '25% off for early-stage startups',
    discountType: 'startup',
    icon: 'Rocket',
    discountPercent: 25,
    applicableProductIds: [],
    applicableTierIds: [],
    excludedAddonIds: [],
    minimumCommitment: 'annual',
    isStackable: false,
    usesPerCustomer: 1,
    eligibility: [
      'Less than 50 employees',
      'Less than $5M in funding',
      'Not primarily an L&D company',
    ],
    verificationMethod: 'manual',
    displayOrder: 3,
    isActive: true,
    showOnPricingPage: true,
    ctaText: 'Apply for Startup Pricing',
    ctaUrl: '/contact?subject=startup',
  },
  {
    id: 'discount-veteran',
    name: 'Veteran/SDVOSB Discount',
    slug: 'veteran',
    description: '15% off for veteran-owned businesses',
    discountType: 'veteran',
    icon: 'Shield',
    discountPercent: 15,
    applicableProductIds: [],
    applicableTierIds: [],
    excludedAddonIds: [],
    minimumCommitment: 'none',
    isStackable: false,
    usesPerCustomer: 1,
    eligibility: [
      'Verified veteran-owned business',
      'SDVOSB certification',
      'SAM.gov registration',
    ],
    verificationMethod: 'sam',
    verificationUrl: 'https://sam.gov',
    displayOrder: 4,
    isActive: true,
    showOnPricingPage: true,
    ctaText: 'Verify Veteran Status',
    ctaUrl: '/contact?subject=veteran',
  },
  {
    id: 'discount-multiyear',
    name: 'Multi-Year Commitment',
    slug: 'multiyear',
    description: 'Additional 10% off for 3-year contracts',
    discountType: 'multiyear',
    icon: 'Calendar',
    discountPercent: 10,
    applicableProductIds: [],
    applicableTierIds: [],
    excludedAddonIds: [],
    minimumCommitment: '3year',
    isStackable: true,
    usesPerCustomer: 1,
    eligibility: ['Commit to a 3-year contract', 'Annual billing required'],
    verificationMethod: 'automatic',
    displayOrder: 5,
    isActive: true,
    showOnPricingPage: true,
    ctaText: 'Contact Sales',
    ctaUrl: '/pricing/enterprise',
  },
];

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

export function getProductBySlug(slug: string): PricingProduct | undefined {
  return products.find((p) => p.slug === slug);
}

export function getTiersByProduct(productId: string): PricingTier[] {
  const product = products.find((p) => p.id === productId);
  return product?.tiers || [];
}

export function getAddonsByProduct(productId: string): PricingAddon[] {
  return addons.filter((a) => a.isActive && a.applicableProductIds.includes(productId));
}

export function getAddonsByCategory(category: string): PricingAddon[] {
  return addons.filter((a) => a.isActive && a.category === category);
}

export function getActiveDiscounts(): PricingDiscount[] {
  return discounts.filter((d) => d.isActive && d.showOnPricingPage);
}
