/**
 * Content Theme Types - Learner-facing content styling
 * Used for courses, webinars, ILT, and other published content
 * NOT for INSPIRE Studio UI theming
 */

export interface ContentThemeColors {
  // Core text/background
  textDark: string;
  textLight: string;
  backgroundDark: string;
  backgroundLight: string;

  // Primary button
  primaryButton: string;
  primaryButtonText: string;

  // Accent colors for charts, highlights, visual interest
  accent2: string;
  accent3: string;
  accent4: string;
  accent5: string;
  accent6: string;

  // Links
  hyperlink: string;
  hyperlinkVisited: string;
}

export interface CustomFont {
  id: string;
  name: string;
  fileName: string;
  format: 'woff2' | 'woff' | 'ttf' | 'otf';
  dataUrl: string; // Base64 encoded font data
  uploadedAt: string;
}

export interface ContentThemeTypography {
  fontFamily: string;
  customFont?: CustomFont; // When using a custom uploaded font
}

export interface ContentThemeStyles {
  borderRadius: 'none' | 'small' | 'medium' | 'large' | 'full';
  shadow: 'none' | 'small' | 'medium' | 'large';
}

export interface ContentThemeBranding {
  logoUrl?: string;
  logoAlt?: string;
  faviconUrl?: string;
}

export interface ContentTheme {
  id: string;
  name: string;
  description?: string;
  colors: ContentThemeColors;
  typography: ContentThemeTypography;
  styles: ContentThemeStyles;
  branding: ContentThemeBranding;
  createdAt: string;
  updatedAt: string;
  createdBy?: string;
  organizationId?: string;
}

// Border radius pixel values
export const BORDER_RADIUS_VALUES: Record<ContentThemeStyles['borderRadius'], string> = {
  none: '0px',
  small: '4px',
  medium: '8px',
  large: '12px',
  full: '9999px',
};

// Shadow presets
export const SHADOW_VALUES: Record<ContentThemeStyles['shadow'], string> = {
  none: 'none',
  small: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
  medium: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
  large: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
};

// Available fonts
export const FONT_OPTIONS = [
  { value: 'Inter, system-ui, sans-serif', label: 'Inter', preview: 'Aa' },
  { value: 'Calibri, sans-serif', label: 'Calibri', preview: 'Aa' },
  { value: 'Arial, sans-serif', label: 'Arial', preview: 'Aa' },
  { value: 'Corbel, sans-serif', label: 'Corbel', preview: 'Aa' },
  { value: 'Candara, sans-serif', label: 'Candara', preview: 'Aa' },
  { value: "'Franklin Gothic Medium', sans-serif", label: 'Franklin Gothic', preview: 'Aa' },
  { value: 'Georgia, serif', label: 'Georgia', preview: 'Aa' },
  { value: "'Times New Roman', serif", label: 'Times New Roman', preview: 'Aa' },
] as const;

// Default content theme
export const DEFAULT_CONTENT_THEME: ContentTheme = {
  id: 'default-content',
  name: 'INSPIRE Default',
  description: 'Clean, professional theme for learning content',
  colors: {
    textDark: '#1a1a2e',
    textLight: '#ffffff',
    backgroundDark: '#1a1a2e',
    backgroundLight: '#ffffff',
    primaryButton: '#0072f5',
    primaryButtonText: '#ffffff',
    accent2: '#f97316', // Orange
    accent3: '#22c55e', // Green
    accent4: '#3b82f6', // Blue
    accent5: '#a855f7', // Purple
    accent6: '#14b8a6', // Teal
    hyperlink: '#0072f5',
    hyperlinkVisited: '#7c3aed',
  },
  typography: {
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  styles: {
    borderRadius: 'medium',
    shadow: 'small',
  },
  branding: {},
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

/**
 * Generate CSS with comments for export
 * Comments explain each property for learning
 */
export function generateThemeCSS(theme: ContentTheme): string {
  // Generate @font-face if custom font is used
  const fontFaceCSS = theme.typography.customFont
    ? `/* Custom Font - Embedded from uploaded file */
@font-face {
  font-family: '${theme.typography.customFont.name}';
  src: url('${theme.typography.customFont.dataUrl}') format('${theme.typography.customFont.format === 'ttf' ? 'truetype' : theme.typography.customFont.format === 'otf' ? 'opentype' : theme.typography.customFont.format}');
  font-weight: normal;
  font-style: normal;
  font-display: swap; /* Ensures text remains visible during font loading */
}

`
    : '';

  return `${fontFaceCSS}/**
 * Content Theme: ${theme.name}
 * ${theme.description || 'Custom theme for learner-facing content'}
 * Generated by INSPIRE Studio Theme Builder
 *
 * HOW TO USE:
 * Import this file into your project, or copy the CSS variables
 * into your existing stylesheet's :root selector.
 */

:root {
  /* ========================================
   * TEXT & BACKGROUND COLORS
   * These control the primary text and background colors
   * ======================================== */

  /* Dark text - used for headings and body text on light backgrounds */
  --text-dark: ${theme.colors.textDark};

  /* Light text - used for text on dark backgrounds */
  --text-light: ${theme.colors.textLight};

  /* Dark background - used for dark sections, headers, footers */
  --background-dark: ${theme.colors.backgroundDark};

  /* Light background - used for main content areas */
  --background-light: ${theme.colors.backgroundLight};

  /* ========================================
   * BUTTON COLORS
   * Primary action buttons and CTAs
   * ======================================== */

  /* Primary button background - your main call-to-action color */
  --primary-button: ${theme.colors.primaryButton};

  /* Primary button text - ensure good contrast with button background */
  --primary-button-text: ${theme.colors.primaryButtonText};

  /* ========================================
   * ACCENT COLORS
   * Used for charts, data visualization, highlights, and visual interest
   * ======================================== */

  /* Accent 2 - Orange - great for warnings, attention-grabbing elements */
  --accent-2: ${theme.colors.accent2};

  /* Accent 3 - Green - success states, completion indicators, positive feedback */
  --accent-3: ${theme.colors.accent3};

  /* Accent 4 - Blue - informational, links, secondary actions */
  --accent-4: ${theme.colors.accent4};

  /* Accent 5 - Purple - creative, premium, special highlights */
  --accent-5: ${theme.colors.accent5};

  /* Accent 6 - Teal - modern, fresh, alternative accent */
  --accent-6: ${theme.colors.accent6};

  /* ========================================
   * LINK COLORS
   * Hyperlink styling for navigation and references
   * ======================================== */

  /* Hyperlink - unvisited link color */
  --hyperlink: ${theme.colors.hyperlink};

  /* Visited hyperlink - helps users track what they've already seen */
  --hyperlink-visited: ${theme.colors.hyperlinkVisited};

  /* ========================================
   * TYPOGRAPHY
   * Font family for all text content
   * ======================================== */

  /* Primary font family - used throughout the content */
  --font-family: ${theme.typography.fontFamily};

  /* ========================================
   * STYLING
   * Border radius and shadow effects
   * ======================================== */

  /* Border radius - controls corner rounding on buttons, cards, inputs */
  --border-radius: ${BORDER_RADIUS_VALUES[theme.styles.borderRadius]};

  /* Box shadow - depth effect for cards, modals, dropdowns */
  --box-shadow: ${SHADOW_VALUES[theme.styles.shadow]};
}

/* ========================================
 * EXAMPLE USAGE
 * ======================================== */

/*
.my-button {
  background-color: var(--primary-button);
  color: var(--primary-button-text);
  border-radius: var(--border-radius);
  box-shadow: var(--box-shadow);
  font-family: var(--font-family);
}

.my-link {
  color: var(--hyperlink);
}

.my-link:visited {
  color: var(--hyperlink-visited);
}

.chart-bar-1 { background-color: var(--accent-2); }
.chart-bar-2 { background-color: var(--accent-3); }
.chart-bar-3 { background-color: var(--accent-4); }
*/
`;
}

/**
 * Generate JSON export with documentation
 */
export function generateThemeJSON(theme: ContentTheme): string {
  return JSON.stringify(
    {
      _documentation: {
        name: 'Content Theme Export',
        description: 'JSON format for importing/exporting INSPIRE Studio content themes',
        version: '1.0',
        generatedAt: new Date().toISOString(),
      },
      theme: {
        id: theme.id,
        name: theme.name,
        description: theme.description,
        colors: {
          _note: 'All colors in HEX format',
          ...theme.colors,
        },
        typography: theme.typography,
        styles: theme.styles,
        branding: theme.branding,
      },
    },
    null,
    2,
  );
}
