/**
 * PDF Export Handler
 *
 * @fileoverview Generates a PDF document from course content
 * @module lib/export/handlers/pdf
 *
 * Note: This handler provides a base implementation that can be enhanced
 * with @react-pdf/renderer for richer PDF generation on the server side.
 */

import type {
  ExportBlockData,
  ExportContext,
  ExportHandler,
  ExportHandlerResult,
  ExportLessonData,
  ExportModuleData,
} from './base';
import { createErrorResult, createSuccessResult, escapeHtml, generateFilename } from './base';

// ============================================================================
// CONSTANTS
// ============================================================================

const PDF_MIME_TYPE = 'text/html'; // Returns HTML for PDF conversion
const PDF_EXTENSION = 'html';

// ============================================================================
// PDF EXPORT HANDLER
// ============================================================================

/**
 * PDF export handler
 *
 * This handler generates a print-optimized HTML document that can be
 * converted to PDF using browser print or server-side tools.
 *
 * For production use, integrate with @react-pdf/renderer or a PDF
 * generation service (e.g., Puppeteer, wkhtmltopdf).
 */
export const pdfHandler: ExportHandler = {
  format: 'pdf',
  displayName: 'PDF Document',
  mimeType: PDF_MIME_TYPE,
  extension: PDF_EXTENSION,

  async export(context: ExportContext): Promise<ExportHandlerResult> {
    const startTime = Date.now();

    try {
      const { courseData } = context;

      // Generate print-optimized HTML
      const htmlContent = generatePrintableHtml(courseData);
      const blob = new Blob([htmlContent], { type: 'text/html' });

      const duration = Date.now() - startTime;

      // Calculate total items (course + modules + lessons + blocks)
      let totalItems = 1; // course
      for (const module of courseData.modules) {
        totalItems++; // module
        for (const lesson of module.lessons) {
          totalItems++; // lesson
          totalItems += lesson.blocks.length; // blocks
        }
      }

      return createSuccessResult({
        blob,
        filename: generateFilename(courseData.title, PDF_EXTENSION),
        mimeType: PDF_MIME_TYPE,
        stats: {
          totalItems,
          totalSize: blob.size,
          duration,
          warnings: 1,
          warningMessages: [
            'Generated as print-optimized HTML. Use browser print (Ctrl+P) to save as PDF.',
          ],
        },
      });
    } catch (error) {
      return createErrorResult({
        error: error instanceof Error ? error.message : 'Unknown error during PDF export',
        errorCode: 'PDF_EXPORT_ERROR',
        duration: Date.now() - startTime,
      });
    }
  },

  validate(context: ExportContext): { valid: boolean; errors: string[] } {
    const errors: string[] = [];

    if (!context.courseData) {
      errors.push('Course data is required');
    }

    if (!context.courseData?.title) {
      errors.push('Course title is required');
    }

    return {
      valid: errors.length === 0,
      errors,
    };
  },
};

// ============================================================================
// HTML GENERATION
// ============================================================================

/**
 * Generate print-optimized HTML document
 */
function generatePrintableHtml(courseData: ExportContext['courseData']): string {
  const contentSections = courseData.modules
    .map((module) => generateModuleSection(module))
    .join('\n');

  const tableOfContents = generateTableOfContents(courseData);

  return `<!DOCTYPE html>
<html lang="${escapeHtml(courseData.language || 'en')}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(courseData.title)} - PDF Export</title>
  <style>
${generatePrintStyles()}
  </style>
</head>
<body>
  <!-- Cover Page -->
  <section class="cover-page">
    <div class="cover-content">
      <h1 class="cover-title">${escapeHtml(courseData.title)}</h1>
      <p class="cover-description">${escapeHtml(courseData.description || '')}</p>
      <div class="cover-meta">
        <p><strong>Version:</strong> ${escapeHtml(courseData.version || '1.0')}</p>
        <p><strong>Duration:</strong> ${courseData.totalDuration} minutes</p>
        <p><strong>Language:</strong> ${escapeHtml(courseData.language || 'English')}</p>
        ${courseData.metadata?.author?.name ? `<p><strong>Author:</strong> ${escapeHtml(courseData.metadata.author.name)}</p>` : ''}
      </div>
    </div>
    <div class="cover-footer">
      <p>Generated by LXD360 INSPIRE Studio</p>
      <p>${new Date().toLocaleDateString()}</p>
    </div>
  </section>

  <!-- Table of Contents -->
  <section class="toc-page">
    <h2 class="toc-title">Table of Contents</h2>
    ${tableOfContents}
  </section>

  <!-- Course Content -->
  ${contentSections}

  <!-- Footer -->
  <footer class="document-footer">
    <p>${escapeHtml(courseData.metadata?.copyright || `${new Date().getFullYear()} All Rights Reserved`)}</p>
  </footer>

  <script>
    // Auto-trigger print dialog when opened
    if (window.location.search.includes('print=true')) {
      window.onload = function() {
        window.print();
      };
    }
  </script>
</body>
</html>`;
}

/**
 * Generate table of contents
 */
function generateTableOfContents(courseData: ExportContext['courseData']): string {
  let pageNum = 3; // Start after cover and TOC

  const entries = courseData.modules
    .map((module, moduleIndex) => {
      const moduleNum = moduleIndex + 1;
      const moduleEntry = `
        <li class="toc-module">
          <span class="toc-number">${moduleNum}.</span>
          <span class="toc-text">${escapeHtml(module.title)}</span>
          <span class="toc-dots"></span>
          <span class="toc-page">${pageNum}</span>
        </li>`;

      const lessonEntries = module.lessons
        .map((lesson, lessonIndex) => {
          pageNum++;
          return `
          <li class="toc-lesson">
            <span class="toc-number">${moduleNum}.${lessonIndex + 1}</span>
            <span class="toc-text">${escapeHtml(lesson.title)}</span>
            <span class="toc-dots"></span>
            <span class="toc-page">${pageNum}</span>
          </li>`;
        })
        .join('\n');

      pageNum++;

      return `
        ${moduleEntry}
        <ul class="toc-lessons">
          ${lessonEntries}
        </ul>`;
    })
    .join('\n');

  return `<nav class="toc"><ol class="toc-list">${entries}</ol></nav>`;
}

/**
 * Generate module section
 */
function generateModuleSection(module: ExportModuleData): string {
  const lessonSections = module.lessons
    .map((lesson) => generateLessonSection(lesson, module))
    .join('\n');

  return `
    <section class="module-section">
      <header class="module-header">
        <h2 class="module-title">${escapeHtml(module.title)}</h2>
        ${module.description ? `<p class="module-description">${escapeHtml(module.description)}</p>` : ''}
      </header>
      ${lessonSections}
    </section>
  `;
}

/**
 * Generate lesson section
 */
function generateLessonSection(lesson: ExportLessonData, module: ExportModuleData): string {
  const blocksHtml = lesson.blocks
    .sort((a, b) => a.order - b.order)
    .map((block) => renderBlockForPdf(block))
    .join('\n');

  return `
    <article class="lesson-section">
      <header class="lesson-header">
        <h3 class="lesson-title">${escapeHtml(lesson.title)}</h3>
        ${lesson.description ? `<p class="lesson-description">${escapeHtml(lesson.description)}</p>` : ''}
        <p class="lesson-meta">
          <span class="meta-module">${escapeHtml(module.title)}</span>
          <span class="meta-duration">${lesson.duration} min</span>
        </p>
      </header>
      <div class="lesson-content">
        ${blocksHtml}
      </div>
    </article>
  `;
}

/**
 * Render content block for PDF
 */
function renderBlockForPdf(block: ExportBlockData): string {
  const content = block.content;

  switch (block.type) {
    case 'paragraph':
      return `<p class="block-paragraph">${escapeHtml(String(content.text || ''))}</p>`;

    case 'heading':
      const level = Math.min(6, Math.max(1, Number(content.level) || 2));
      return `<h${level} class="block-heading">${escapeHtml(String(content.text || ''))}</h${level}>`;

    case 'image':
      return `<figure class="block-image">
        <img src="${escapeHtml(String(content.url || ''))}" alt="${escapeHtml(String(content.alt || ''))}" />
        ${content.caption ? `<figcaption>${escapeHtml(String(content.caption))}</figcaption>` : ''}
      </figure>`;

    case 'video':
      return `<div class="block-video">
        <p class="video-reference">[Video: ${escapeHtml(String(content.title || 'Video content'))}]</p>
        ${content.url ? `<p class="video-url">URL: ${escapeHtml(String(content.url))}</p>` : ''}
      </div>`;

    case 'quote':
      return `<blockquote class="block-quote">
        <p>${escapeHtml(String(content.text || ''))}</p>
        ${content.author ? `<cite>- ${escapeHtml(String(content.author))}</cite>` : ''}
      </blockquote>`;

    case 'list':
      const items = Array.isArray(content.items) ? content.items : [];
      const listItems = items.map((item) => `<li>${escapeHtml(String(item))}</li>`).join('\n');
      const tag = content.ordered ? 'ol' : 'ul';
      return `<${tag} class="block-list">${listItems}</${tag}>`;

    case 'divider':
      return '<hr class="block-divider" />';

    case 'accordion':
      const sections = Array.isArray(content.sections) ? content.sections : [];
      return sections
        .map(
          (section: { title?: string; content?: string }) =>
            `<div class="block-accordion-section">
            <h4>${escapeHtml(String(section.title || 'Section'))}</h4>
            <p>${escapeHtml(String(section.content || ''))}</p>
          </div>`,
        )
        .join('\n');

    case 'tabs':
      const tabs = Array.isArray(content.tabs) ? content.tabs : [];
      return tabs
        .map(
          (tab: { title?: string; content?: string }) =>
            `<div class="block-tab-section">
            <h4>${escapeHtml(String(tab.title || 'Tab'))}</h4>
            <p>${escapeHtml(String(tab.content || ''))}</p>
          </div>`,
        )
        .join('\n');

    case 'mc-question':
      const choices = Array.isArray(content.choices) ? content.choices : [];
      const choiceList = choices
        .map(
          (choice: { text?: string }, i: number) =>
            `<li>${String.fromCharCode(65 + i)}. ${escapeHtml(String(choice.text || ''))}</li>`,
        )
        .join('\n');
      return `<div class="block-question">
        <p class="question-label"><strong>Question:</strong></p>
        <p class="question-text">${escapeHtml(String(content.question || ''))}</p>
        <ol class="question-choices" type="A">${choiceList}</ol>
      </div>`;

    case 'fitb-question':
      return `<div class="block-question">
        <p class="question-label"><strong>Fill in the Blank:</strong></p>
        <p class="question-text">${escapeHtml(String(content.template || ''))}</p>
      </div>`;

    default:
      return `<div class="block-unknown">[Content: ${escapeHtml(block.type)}]</div>`;
  }
}

/**
 * Generate print-optimized CSS styles
 */
function generatePrintStyles(): string {
  return `
    /* Reset & Base */
    *, *::before, *::after {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }

    html {
      font-size: 12pt;
      line-height: 1.5;
    }

    body {
      font-family: 'Georgia', 'Times New Roman', serif;
      color: #000;
      background: #fff;
    }

    /* Print Settings */
    @page {
      size: A4;
      margin: 2cm;
    }

    @media print {
      .cover-page {
        page-break-after: always;
      }

      .toc-page {
        page-break-after: always;
      }

      .module-section {
        page-break-before: always;
      }

      .lesson-section {
        page-break-inside: avoid;
      }

      h1, h2, h3, h4, h5, h6 {
        page-break-after: avoid;
      }

      img {
        max-width: 100%;
        page-break-inside: avoid;
      }
    }

    /* Cover Page */
    .cover-page {
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      justify-content: center;
      text-align: center;
      padding: 2cm;
    }

    .cover-title {
      font-size: 2.5em;
      font-weight: bold;
      margin-bottom: 1em;
      color: #0072f5;
    }

    .cover-description {
      font-size: 1.2em;
      color: #333;
      max-width: 80%;
      margin: 0 auto 2em;
    }

    .cover-meta {
      font-size: 0.9em;
      color: #666;
    }

    .cover-meta p {
      margin: 0.5em 0;
    }

    .cover-footer {
      margin-top: auto;
      font-size: 0.8em;
      color: #999;
    }

    /* Table of Contents */
    .toc-page {
      padding: 2em 0;
    }

    .toc-title {
      font-size: 1.5em;
      margin-bottom: 1.5em;
      text-align: center;
      color: #0072f5;
    }

    .toc-list {
      list-style: none;
    }

    .toc-module,
    .toc-lesson {
      display: flex;
      align-items: baseline;
      padding: 0.3em 0;
    }

    .toc-module {
      font-weight: bold;
      margin-top: 0.8em;
    }

    .toc-lessons {
      list-style: none;
      margin-left: 1.5em;
    }

    .toc-number {
      min-width: 2em;
    }

    .toc-text {
      flex: 0 0 auto;
    }

    .toc-dots {
      flex: 1;
      border-bottom: 1px dotted #ccc;
      margin: 0 0.5em;
      min-width: 2em;
    }

    .toc-page {
      flex: 0 0 auto;
      color: #666;
    }

    /* Module & Lesson Sections */
    .module-section {
      margin-top: 2em;
    }

    .module-header {
      background: #f0f4f8;
      padding: 1.5em;
      margin-bottom: 1.5em;
      border-left: 4px solid #0072f5;
    }

    .module-title {
      font-size: 1.4em;
      color: #001d3d;
      margin-bottom: 0.5em;
    }

    .module-description {
      color: #444;
    }

    .lesson-section {
      margin: 1.5em 0;
      padding: 1em;
      border: 1px solid #e2e8f0;
      border-radius: 4px;
    }

    .lesson-header {
      border-bottom: 1px solid #e2e8f0;
      padding-bottom: 0.8em;
      margin-bottom: 1em;
    }

    .lesson-title {
      font-size: 1.2em;
      color: #0072f5;
      margin-bottom: 0.3em;
    }

    .lesson-description {
      color: #666;
      font-size: 0.9em;
    }

    .lesson-meta {
      font-size: 0.8em;
      color: #999;
      margin-top: 0.5em;
    }

    .meta-module::after {
      content: ' | ';
    }

    /* Content Blocks */
    .lesson-content > * {
      margin-bottom: 1em;
    }

    .block-paragraph {
      text-align: justify;
    }

    .block-heading {
      color: #001d3d;
      margin-top: 1em;
      margin-bottom: 0.5em;
    }

    .block-image {
      text-align: center;
      margin: 1.5em 0;
    }

    .block-image img {
      max-width: 100%;
      max-height: 400px;
      border: 1px solid #ddd;
    }

    .block-image figcaption {
      font-size: 0.85em;
      color: #666;
      font-style: italic;
      margin-top: 0.5em;
    }

    .block-video {
      background: #f5f5f5;
      padding: 1em;
      border: 1px solid #ddd;
      text-align: center;
    }

    .video-reference {
      font-weight: bold;
    }

    .video-url {
      font-size: 0.8em;
      color: #666;
      word-break: break-all;
    }

    .block-quote {
      border-left: 3px solid #0072f5;
      padding-left: 1em;
      font-style: italic;
      color: #444;
      margin: 1em 0;
    }

    .block-quote cite {
      display: block;
      margin-top: 0.5em;
      font-size: 0.9em;
      color: #666;
    }

    .block-list {
      padding-left: 2em;
    }

    .block-list li {
      margin: 0.3em 0;
    }

    .block-divider {
      border: none;
      border-top: 1px solid #ccc;
      margin: 1.5em 0;
    }

    .block-accordion-section,
    .block-tab-section {
      background: #f9f9f9;
      padding: 0.8em;
      margin: 0.5em 0;
      border: 1px solid #eee;
    }

    .block-accordion-section h4,
    .block-tab-section h4 {
      font-size: 1em;
      color: #0072f5;
      margin-bottom: 0.5em;
    }

    .block-question {
      background: #fff8e1;
      padding: 1em;
      border: 1px solid #ffe082;
      border-radius: 4px;
    }

    .question-label {
      color: #f57c00;
      margin-bottom: 0.5em;
    }

    .question-choices {
      margin-left: 1.5em;
      margin-top: 0.5em;
    }

    /* Footer */
    .document-footer {
      margin-top: 2em;
      padding-top: 1em;
      border-top: 1px solid #ccc;
      text-align: center;
      font-size: 0.8em;
      color: #666;
    }
  `;
}

export default pdfHandler;
