import {
  Activity,
  Award,
  BarChart3,
  Bell,
  Bookmark,
  BookOpen,
  Bot,
  Briefcase,
  Calendar,
  ChevronDown,
  Code,
  Command,
  Edit3,
  Eye,
  FileText,
  Film,
  Folder,
  FolderHeart,
  FolderOpen,
  Gauge,
  GraduationCap,
  HelpCircle,
  LayoutDashboard,
  LayoutTemplate,
  ListTodo,
  Mail,
  Menu,
  Play,
  Plus,
  Server,
  Settings,
  Sparkles,
  Star,
  Terminal,
  TrendingUp,
  Trophy,
  Users,
  Video,
  X,
  Zap,
} from 'lucide-react';

// Map of icon name strings to React components
export const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  LayoutDashboard,
  BookOpen,
  FolderOpen,
  Play,
  Trophy,
  Briefcase,
  Users,
  Award,
  BarChart3,
  FileText,
  TrendingUp,
  Settings,
  Edit3,
  Server,
  Activity,
  Plus,
  Sparkles,
  Folder,
  FolderHeart,
  LayoutTemplate,
  Star,
  HelpCircle,
  Bookmark,
  GraduationCap,
  Bell,
  ChevronDown,
  Menu,
  X,
  Eye,
  Bot,
  Zap,
  Video,
  Film,
  Code,
  Mail,
  Calendar,
  ListTodo,
  Gauge,
  Terminal,
  Command,
};

/**
 * Get an icon component by name
 * @param iconName - The name of the icon (must match a Lucide icon name)
 * @returns The React icon component or a default icon if not found
 */
export function getIcon(iconName: string): React.ComponentType<{ className?: string }> {
  return iconMap[iconName] || LayoutDashboard;
}
